import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from "@nestjs/common";
import { Prisma } from "@prisma/assurerail-client";
import { randomUUID } from "node:crypto";
import { sha256Digest, toCanonicalValue } from "../contracts/v1";
import { InstitutionAccessService } from "../institutions/institution-access.service";
import { StepUpService } from "../institutions/step-up.service";
import { InternalAccessService } from "../internal-access/internal-access.service";
import type { InternalPermission } from "../internal-access/internal-access-policy";
import { inspectPersistenceFlags } from "../persistence/feature-flags";
import { PrismaService } from "../store/prisma.service";
import { calculateExactFee, exactMinor, type ExactFeeRule } from "./fee-calculation";

export type ParticipantOpsActor = { actorUserId: string; actorSessionId: string; actingInstitutionId: string };
export type InternalOpsActor = { actorUserId: string; actorSessionId: string };
const CONTRACT_CHANGES = ["RENEW", "SUSPEND", "TERMINATE", "REINSTATE"] as const;
const ROUTES = ["DA", "PTC"] as const; const REPRESENTATIONS = ["CONVENTIONAL", "TOKENISED"] as const;
const LEGS = ["INITIAL_TRANSFER_OR_ISSUE", "SECONDARY_TRANSFER_OR_TRADE"] as const;
const FEE_BASES = ["FIXED_MINOR", "NOTIONAL_BASIS_POINTS", "PER_UNIT_MINOR"] as const;

function enabled(): void { if (inspectPersistenceFlags(process.env).customerOperations !== "shadow") throw new ForbiddenException("customer operations are disabled"); }
function required(value: unknown, name: string, max = 1_000): string { if (typeof value !== "string" || !value.trim()) throw new BadRequestException(`${name} is required`); const result = value.trim(); if (result.length > max) throw new BadRequestException(`${name} exceeds ${max} characters`); return result; }
function oneOf(value: unknown, name: string, allowed: readonly string[]): string { const result = required(value, name, 100); if (!allowed.includes(result)) throw new BadRequestException(`${name} must be one of: ${allowed.join(", ")}`); return result; }
function date(value: unknown, name: string): Date { const result = new Date(required(value, name, 80)); if (!Number.isFinite(result.getTime())) throw new BadRequestException(`${name} must be ISO-8601`); return result; }
function json(value: unknown): Prisma.InputJsonValue { return toCanonicalValue(value ?? {}) as unknown as Prisma.InputJsonValue; }
function digest(value: unknown, name: string): string { const result = required(value, name, 80); if (!/^sha256:[a-f0-9]{64}$/.test(result)) throw new BadRequestException(`${name} must be a lowercase sha256 digest`); return result; }
function exact(value: unknown, name: string, positive = false): string { try { return exactMinor(value, name, !positive); } catch (error) { throw new BadRequestException((error as Error).message); } }
function scale(value: unknown, name: string): number { if (!Number.isInteger(value) || (value as number) < 0 || (value as number) > 9) throw new BadRequestException(`${name} must be an integer from 0 to 9`); return value as number; }

@Injectable()
export class CustomerOperationsService {
  constructor(private readonly db: PrismaService, private readonly participantAccess: InstitutionAccessService, private readonly internalAccess: InternalAccessService, private readonly stepUp: StepUpService) {}

  async participantOverview(actor: ParticipantOpsActor) {
    enabled(); await this.participant(actor, "VIEW_CUSTOMER_OPERATIONS"); const institutionId = actor.actingInstitutionId;
    const [contracts, cohorts, requests, reviews, exits] = await Promise.all([
      this.db.customerContract.findMany({
        where: { institutionId, status: { notIn: ["PROPOSED", "REJECTED"] } },
        include: {
          rateCards: {
            where: { status: { notIn: ["PROPOSED", "REJECTED"] } },
            include: { feeRules: true },
            orderBy: { version: "desc" },
          },
          invoiceStatements: {
            where: { status: { not: "DRAFT" } },
            include: {
              lines: true,
              creditCorrections: { where: { status: "APPROVED" } },
            },
            orderBy: { periodEnd: "desc" },
          },
          changes: { where: { status: "APPROVED" }, orderBy: { proposedAt: "desc" } },
        },
        orderBy: { createdAt: "desc" },
      }),
      this.db.customerImplementationCohort.findMany({ where: { institutionId }, orderBy: { createdAt: "desc" } }),
      this.db.customerServiceRequest.findMany({ where: { institutionId }, include: { messages: { orderBy: { createdAt: "asc" } } }, orderBy: { createdAt: "desc" } }),
      this.db.customerOperationalReview.findMany({ where: { institutionId }, orderBy: { periodEnd: "desc" } }),
      this.db.customerDataExitExport.findMany({ where: { institutionId }, orderBy: { createdAt: "desc" } }),
    ]);
    return { institutionId, pricingChangesAuthority: false as const, transactionAuthorityAffected: false as const, contracts, cohorts, serviceRequests: requests, operationalReviews: reviews, exitExports: exits };
  }

  async proposeContract(actor: InternalOpsActor, institutionId: string, body: { contractRef?: unknown; currency?: unknown; currencyScale?: unknown; termsDigest?: unknown; termsEvidenceRef?: unknown; effectiveAt?: unknown; expiresAt?: unknown; renewalReviewAt?: unknown; stepUpEvidenceId?: unknown }) {
    enabled(); await this.internal(actor, "COMMERCIAL_CONTRACT_PROPOSE"); const institution = await this.db.institution.findUnique({ where: { id: institutionId }, include: { admission: true } });
    if (!institution || institution.status !== "ACTIVE" || institution.admission?.status !== "ADMITTED") throw new BadRequestException("an admitted active institution is required");
    const contractRef = required(body.contractRef, "contractRef", 160); const currency = required(body.currency, "currency", 3).toUpperCase(); if (!/^[A-Z]{3}$/.test(currency)) throw new BadRequestException("currency must be ISO-4217 alpha-3");
    const effectiveAt = date(body.effectiveAt, "effectiveAt"); const expiresAt = date(body.expiresAt, "expiresAt"); const renewalReviewAt = date(body.renewalReviewAt, "renewalReviewAt"); if (!(effectiveAt < renewalReviewAt && renewalReviewAt < expiresAt)) throw new BadRequestException("contract dates must be effectiveAt < renewalReviewAt < expiresAt");
    const stepUpEvidenceId = required(body.stepUpEvidenceId, "stepUpEvidenceId", 160); const latest = await this.db.customerContract.findFirst({ where: { institutionId, contractRef }, orderBy: { version: "desc" } });
    return this.db.$transaction(async (tx) => { await this.consumeInternal(tx, actor, "INTERNAL_CONTRACT_PROPOSE", stepUpEvidenceId); return tx.customerContract.create({ data: { id: `cctr_${randomUUID()}`, institutionId, contractRef, version: (latest?.version ?? 0) + 1, currency, currencyScale: scale(body.currencyScale, "currencyScale"), termsDigest: digest(body.termsDigest, "termsDigest"), termsEvidenceRef: required(body.termsEvidenceRef, "termsEvidenceRef", 500), proposedByUserId: actor.actorUserId, proposalStepUpId: stepUpEvidenceId, effectiveAt, expiresAt, renewalReviewAt } }); });
  }

  async reviewContract(actor: InternalOpsActor, institutionId: string, contractId: string, body: { decision?: unknown; reason?: unknown; stepUpEvidenceId?: unknown }) {
    enabled(); await this.internal(actor, "COMMERCIAL_CONTRACT_REVIEW"); const contract = await this.contract(institutionId, contractId); if (contract.status !== "PROPOSED") throw new ConflictException("only a proposed contract can be reviewed"); if (contract.proposedByUserId === actor.actorUserId) throw new ForbiddenException("contract proposer cannot review the same proposal");
    const decision = oneOf(body.decision, "decision", ["APPROVE", "REJECT"]); const stepUpEvidenceId = required(body.stepUpEvidenceId, "stepUpEvidenceId", 160); const now = new Date();
    return this.db.$transaction(async (tx) => { await this.consumeInternal(tx, actor, "INTERNAL_CONTRACT_REVIEW", stepUpEvidenceId); const claimed = await tx.customerContract.updateMany({ where: { id: contractId, status: "PROPOSED" }, data: { status: decision === "APPROVE" ? "APPROVED_PENDING_CUSTOMER" : "REJECTED", reviewedByUserId: actor.actorUserId, reviewStepUpId: stepUpEvidenceId, reviewReason: required(body.reason, "reason", 1_000), reviewedAt: now } }); if (claimed.count !== 1) throw new ConflictException("contract review was concurrently decided"); return tx.customerContract.findUniqueOrThrow({ where: { id: contractId } }); });
  }

  async acknowledgeContract(actor: ParticipantOpsActor, contractId: string, body: { stepUpEvidenceId?: unknown }) {
    enabled(); const authority = await this.participant(actor, "MANAGE_CUSTOMER_OPERATIONS"); const contract = await this.contract(actor.actingInstitutionId, contractId); if (contract.status !== "APPROVED_PENDING_CUSTOMER") throw new ConflictException("contract is not awaiting participant acceptance");
    const now = new Date(); if (contract.expiresAt <= now) throw new ConflictException("contract term has expired"); const stepUpEvidenceId = required(body.stepUpEvidenceId, "stepUpEvidenceId", 160);
    return this.db.$transaction(async (tx) => { await this.stepUp.consume({ evidenceId: stepUpEvidenceId, userId: actor.actorUserId, sessionId: actor.actorSessionId, purpose: "CUSTOMER_CONTRACT_ACKNOWLEDGE", institutionId: actor.actingInstitutionId }, tx); const claimed = await tx.customerContract.updateMany({ where: { id: contractId, status: "APPROVED_PENDING_CUSTOMER" }, data: { status: "ACTIVE_SHADOW", participantAcceptedByUserId: actor.actorUserId, participantMandateId: authority.mandateId!, participantStepUpId: stepUpEvidenceId, participantAcceptedAt: now } }); if (claimed.count !== 1) throw new ConflictException("contract acceptance was concurrently decided"); return tx.customerContract.findUniqueOrThrow({ where: { id: contractId } }); });
  }

  async proposeContractChange(actor: InternalOpsActor, institutionId: string, contractId: string, body: { changeType?: unknown; proposedValues?: unknown; reason?: unknown; evidenceRef?: unknown; stepUpEvidenceId?: unknown }) {
    enabled(); await this.internal(actor, "COMMERCIAL_CONTRACT_PROPOSE"); const contract = await this.contract(institutionId, contractId); const changeType = oneOf(body.changeType, "changeType", CONTRACT_CHANGES); this.validateContractChange(contract, changeType, body.proposedValues);
    const proposedValues = json(body.proposedValues); const reason = required(body.reason, "reason", 1_000); const evidenceRef = required(body.evidenceRef, "evidenceRef", 500); const stepUpEvidenceId = required(body.stepUpEvidenceId, "stepUpEvidenceId", 160); const proposalDigest = sha256Digest({ contractId, fromStatus: contract.status, changeType, proposedValues, reason, evidenceRef });
    return this.db.$transaction(async (tx) => { await this.consumeInternal(tx, actor, "INTERNAL_CONTRACT_PROPOSE", stepUpEvidenceId); return tx.customerContractChange.create({ data: { id: `cchg_${randomUUID()}`, customerContractId: contractId, changeType, fromStatus: contract.status, proposedValues, reason, evidenceRef, proposalDigest, proposedByUserId: actor.actorUserId, proposalStepUpId: stepUpEvidenceId } }); });
  }

  async reviewContractChange(actor: InternalOpsActor, institutionId: string, changeId: string, body: { decision?: unknown; reason?: unknown; stepUpEvidenceId?: unknown }) {
    enabled(); await this.internal(actor, "COMMERCIAL_CONTRACT_REVIEW"); const change = await this.db.customerContractChange.findUnique({ where: { id: changeId }, include: { customerContract: true } }); if (!change || change.customerContract.institutionId !== institutionId) throw new NotFoundException("contract change not found"); if (change.status !== "PROPOSED") throw new ConflictException("contract change is not pending"); if (change.proposedByUserId === actor.actorUserId) throw new ForbiddenException("change proposer cannot review the same proposal"); if (change.customerContract.status !== change.fromStatus) throw new ConflictException("contract state changed after this proposal");
    const decision = oneOf(body.decision, "decision", ["APPROVE", "REJECT"]); const stepUpEvidenceId = required(body.stepUpEvidenceId, "stepUpEvidenceId", 160); const now = new Date();
    return this.db.$transaction(async (tx) => { await this.consumeInternal(tx, actor, "INTERNAL_CONTRACT_REVIEW", stepUpEvidenceId); if (decision === "APPROVE") { const contractClaim = await tx.customerContract.updateMany({ where: { id: change.customerContractId, status: change.fromStatus }, data: this.appliedContractChange(change.changeType, change.proposedValues) }); if (contractClaim.count !== 1) throw new ConflictException("contract state changed while applying this proposal"); } const changeClaim = await tx.customerContractChange.updateMany({ where: { id: changeId, status: "PROPOSED" }, data: { status: decision === "APPROVE" ? "APPROVED" : "REJECTED", reviewedByUserId: actor.actorUserId, reviewStepUpId: stepUpEvidenceId, reviewReason: required(body.reason, "reason", 1_000), reviewedAt: now, appliedAt: decision === "APPROVE" ? now : null } }); if (changeClaim.count !== 1) throw new ConflictException("contract change was concurrently decided"); return tx.customerContractChange.findUniqueOrThrow({ where: { id: changeId } }); });
  }

  async proposeRateCard(actor: InternalOpsActor, institutionId: string, contractId: string, body: { effectiveAt?: unknown; expiresAt?: unknown; rules?: unknown; stepUpEvidenceId?: unknown }) {
    enabled(); await this.internal(actor, "COMMERCIAL_RATE_CARD_PROPOSE"); const contract = await this.contract(institutionId, contractId); const effectiveAt = date(body.effectiveAt, "effectiveAt"); const expiresAt = date(body.expiresAt, "expiresAt"); if (effectiveAt < contract.effectiveAt || expiresAt > contract.expiresAt || expiresAt <= effectiveAt) throw new BadRequestException("rate-card term must be within the contract term"); const rules = this.feeRules(body.rules); const latest = await this.db.customerRateCard.findFirst({ where: { customerContractId: contractId }, orderBy: { version: "desc" } }); const version = (latest?.version ?? 0) + 1; const rateCardDigest = sha256Digest({ contractId, version, effectiveAt: effectiveAt.toISOString(), expiresAt: expiresAt.toISOString(), rules }); const stepUpEvidenceId = required(body.stepUpEvidenceId, "stepUpEvidenceId", 160);
    return this.db.$transaction(async (tx) => { await this.consumeInternal(tx, actor, "INTERNAL_RATE_CARD_PROPOSE", stepUpEvidenceId); return tx.customerRateCard.create({ data: { id: `rate_${randomUUID()}`, customerContractId: contractId, version, effectiveAt, expiresAt, rateCardDigest, proposedByUserId: actor.actorUserId, proposalStepUpId: stepUpEvidenceId, feeRules: { create: rules.map((rule) => ({ id: `frule_${randomUUID()}`, ...rule })) } }, include: { feeRules: true } }); });
  }

  async reviewRateCard(actor: InternalOpsActor, institutionId: string, rateCardId: string, body: { decision?: unknown; reason?: unknown; stepUpEvidenceId?: unknown }) {
    enabled(); await this.internal(actor, "COMMERCIAL_RATE_CARD_REVIEW"); const card = await this.db.customerRateCard.findUnique({ where: { id: rateCardId }, include: { customerContract: true } }); if (!card || card.customerContract.institutionId !== institutionId) throw new NotFoundException("rate card not found"); if (card.status !== "PROPOSED") throw new ConflictException("rate card is not pending"); if (card.proposedByUserId === actor.actorUserId) throw new ForbiddenException("rate-card proposer cannot review the same proposal"); const decision = oneOf(body.decision, "decision", ["APPROVE", "REJECT"]); const stepUpEvidenceId = required(body.stepUpEvidenceId, "stepUpEvidenceId", 160); const now = new Date();
    return this.db.$transaction(async (tx) => { await this.consumeInternal(tx, actor, "INTERNAL_RATE_CARD_REVIEW", stepUpEvidenceId); const claimed = await tx.customerRateCard.updateMany({ where: { id: rateCardId, status: "PROPOSED" }, data: { status: decision === "APPROVE" ? "APPROVED_SHADOW" : "REJECTED", reviewedByUserId: actor.actorUserId, reviewStepUpId: stepUpEvidenceId, reviewReason: required(body.reason, "reason", 1_000), reviewedAt: now } }); if (claimed.count !== 1) throw new ConflictException("rate-card review was concurrently decided"); if (decision === "APPROVE") await tx.customerRateCard.updateMany({ where: { customerContractId: card.customerContractId, id: { not: rateCardId }, status: "APPROVED_SHADOW" }, data: { status: "SUPERSEDED" } }); return tx.customerRateCard.findUniqueOrThrow({ where: { id: rateCardId } }); });
  }

  async recordUsage(actor: InternalOpsActor, institutionId: string, body: { customerContractId?: unknown; transactionCaseId?: unknown; sourceEventRef?: unknown; sourceEventDigest?: unknown; transactionRoute?: unknown; representation?: unknown; lifecycleLeg?: unknown; metric?: unknown; quantityMinor?: unknown; notionalMinor?: unknown; currency?: unknown; occurredAt?: unknown; stepUpEvidenceId?: unknown }) {
    enabled(); await this.internal(actor, "COMMERCIAL_USAGE_RECORD"); const contract = await this.contract(institutionId, required(body.customerContractId, "customerContractId", 160)); if (contract.status !== "ACTIVE_SHADOW") throw new ConflictException("usage requires an active shadow contract"); const occurredAt = date(body.occurredAt, "occurredAt"); if (occurredAt < contract.effectiveAt || occurredAt >= contract.expiresAt) throw new BadRequestException("usage occurred outside the contract term"); const stepUpEvidenceId = required(body.stepUpEvidenceId, "stepUpEvidenceId", 160);
    const data = { id: `usage_${randomUUID()}`, institutionId, customerContractId: contract.id, transactionCaseId: body.transactionCaseId ? required(body.transactionCaseId, "transactionCaseId", 160) : null, sourceEventRef: required(body.sourceEventRef, "sourceEventRef", 240), sourceEventDigest: digest(body.sourceEventDigest, "sourceEventDigest"), transactionRoute: oneOf(body.transactionRoute, "transactionRoute", ROUTES), representation: oneOf(body.representation, "representation", REPRESENTATIONS), lifecycleLeg: oneOf(body.lifecycleLeg, "lifecycleLeg", LEGS), metric: required(body.metric, "metric", 120), quantityMinor: exact(body.quantityMinor, "quantityMinor"), notionalMinor: exact(body.notionalMinor, "notionalMinor"), currency: required(body.currency, "currency", 3).toUpperCase(), occurredAt, recordedByUserId: actor.actorUserId };
    if (!/^[A-Z]{3}$/.test(data.currency) || data.currency !== contract.currency) throw new BadRequestException("usage currency must be ISO-4217 alpha-3 and match contract currency");
    if (data.transactionCaseId) await this.requireInstitutionCase(institutionId, data.transactionCaseId);
    try { return await this.db.$transaction(async (tx) => { await this.consumeInternal(tx, actor, "INTERNAL_USAGE_RECORD", stepUpEvidenceId); return tx.customerUsageEvent.create({ data }); }); } catch (error) { if ((error as { code?: string }).code === "P2002") throw new ConflictException("source event was already metered for this institution"); throw error; }
  }

  async prepareInvoice(actor: InternalOpsActor, institutionId: string, body: { customerContractId?: unknown; customerRateCardId?: unknown; statementRef?: unknown; periodStart?: unknown; periodEnd?: unknown; stepUpEvidenceId?: unknown }) {
    enabled(); await this.internal(actor, "COMMERCIAL_INVOICE_PREPARE"); const contract = await this.contract(institutionId, required(body.customerContractId, "customerContractId", 160)); const card = await this.db.customerRateCard.findUnique({ where: { id: required(body.customerRateCardId, "customerRateCardId", 160) }, include: { feeRules: true } }); if (!card || card.customerContractId !== contract.id || card.status !== "APPROVED_SHADOW") throw new BadRequestException("approved contract rate card required"); const periodStart = date(body.periodStart, "periodStart"); const periodEnd = date(body.periodEnd, "periodEnd"); if (periodEnd <= periodStart || periodStart < card.effectiveAt || periodEnd > card.expiresAt) throw new BadRequestException("statement period must be ordered and within rate-card term");
    const events = await this.db.customerUsageEvent.findMany({ where: { customerContractId: contract.id, status: "UNBILLED", occurredAt: { gte: periodStart, lt: periodEnd } }, orderBy: [{ occurredAt: "asc" }, { id: "asc" }] }); if (!events.length) throw new ConflictException("no unbilled usage exists for this statement period"); const lines = events.map((event) => { const rule = card.feeRules.find((item) => item.transactionRoute === event.transactionRoute && item.representation === event.representation && item.lifecycleLeg === event.lifecycleLeg && item.metric === event.metric); if (!rule) throw new ConflictException(`no fee rule for usage event ${event.id}`); const calculation = calculateExactFee(rule as ExactFeeRule, event); return { event, rule, calculation, calculationDigest: sha256Digest({ eventId: event.id, ruleId: rule.id, basisMinor: calculation.basisMinor, rateValue: rule.rateValue, calculatedFeeMinor: calculation.feeMinor }) }; }); const gross = lines.reduce((sum, line) => sum + BigInt(line.calculation.feeMinor), 0n).toString(); const statementRef = required(body.statementRef, "statementRef", 160); const statementDigest = sha256Digest({ contractId: contract.id, rateCardId: card.id, statementRef, periodStart: periodStart.toISOString(), periodEnd: periodEnd.toISOString(), grossFeeMinor: gross, lines: lines.map((line) => ({ usageEventId: line.event.id, feeRuleId: line.rule.id, ...line.calculation, calculationDigest: line.calculationDigest })) }); const stepUpEvidenceId = required(body.stepUpEvidenceId, "stepUpEvidenceId", 160);
    return this.db.$transaction(async (tx) => { await this.consumeInternal(tx, actor, "INTERNAL_INVOICE_PREPARE", stepUpEvidenceId); const statement = await tx.customerInvoiceStatement.create({ data: { id: `inv_${randomUUID()}`, customerContractId: contract.id, customerRateCardId: card.id, statementRef, periodStart, periodEnd, currency: contract.currency, currencyScale: contract.currencyScale, grossFeeMinor: gross, creditMinor: "0", netFeeMinor: gross, statementDigest, preparedByUserId: actor.actorUserId, preparationStepUpId: stepUpEvidenceId } }); for (const line of lines) { const claimed = await tx.customerUsageEvent.updateMany({ where: { id: line.event.id, status: "UNBILLED" }, data: { status: "BILLED" } }); if (claimed.count !== 1) throw new ConflictException("usage event changed during statement preparation"); await tx.customerInvoiceLine.create({ data: { id: `iline_${randomUUID()}`, invoiceStatementId: statement.id, usageEventId: line.event.id, feeRuleId: line.rule.id, basisMinor: line.calculation.basisMinor, rateValue: line.rule.rateValue, calculatedFeeMinor: line.calculation.feeMinor, calculationDigest: line.calculationDigest } }); } return tx.customerInvoiceStatement.findUniqueOrThrow({ where: { id: statement.id }, include: { lines: true } }); });
  }

  async issueInvoice(actor: InternalOpsActor, institutionId: string, invoiceId: string, body: { reason?: unknown; stepUpEvidenceId?: unknown }) {
    enabled(); await this.internal(actor, "COMMERCIAL_INVOICE_REVIEW"); const invoice = await this.invoice(institutionId, invoiceId); if (invoice.status !== "DRAFT") throw new ConflictException("only a draft statement can be issued"); if (invoice.preparedByUserId === actor.actorUserId) throw new ForbiddenException("statement preparer cannot issue the same statement"); const stepUpEvidenceId = required(body.stepUpEvidenceId, "stepUpEvidenceId", 160);
    return this.db.$transaction(async (tx) => { await this.consumeInternal(tx, actor, "INTERNAL_INVOICE_REVIEW", stepUpEvidenceId); const claimed = await tx.customerInvoiceStatement.updateMany({ where: { id: invoiceId, status: "DRAFT" }, data: { status: "ISSUED_SHADOW", issuedByUserId: actor.actorUserId, issueStepUpId: stepUpEvidenceId, issueReason: required(body.reason, "reason", 1_000), issuedAt: new Date() } }); if (claimed.count !== 1) throw new ConflictException("statement issuance was concurrently decided"); return tx.customerInvoiceStatement.findUniqueOrThrow({ where: { id: invoiceId } }); });
  }

  async proposeCredit(actor: InternalOpsActor, institutionId: string, invoiceId: string, body: { amountMinor?: unknown; reason?: unknown; evidenceRef?: unknown; stepUpEvidenceId?: unknown }) {
    enabled(); await this.internal(actor, "COMMERCIAL_CREDIT_PROPOSE"); const invoice = await this.invoice(institutionId, invoiceId); if (!["ISSUED_SHADOW", "CORRECTED"].includes(invoice.status)) throw new ConflictException("only an issued statement can receive a credit correction"); const amountMinor = exact(body.amountMinor, "amountMinor", true); if (BigInt(amountMinor) > BigInt(invoice.netFeeMinor)) throw new BadRequestException("credit cannot exceed current net fee"); const reason = required(body.reason, "reason", 1_000); const evidenceRef = required(body.evidenceRef, "evidenceRef", 500); const proposalDigest = sha256Digest({ invoiceId, amountMinor, reason, evidenceRef, currentNetFeeMinor: invoice.netFeeMinor }); const stepUpEvidenceId = required(body.stepUpEvidenceId, "stepUpEvidenceId", 160);
    return this.db.$transaction(async (tx) => { await this.consumeInternal(tx, actor, "INTERNAL_CREDIT_PROPOSE", stepUpEvidenceId); return tx.customerCreditCorrection.create({ data: { id: `credit_${randomUUID()}`, customerContractId: invoice.customerContractId, invoiceStatementId: invoiceId, amountMinor, reason, evidenceRef, proposalDigest, proposedByUserId: actor.actorUserId, proposalStepUpId: stepUpEvidenceId } }); });
  }

  async reviewCredit(actor: InternalOpsActor, institutionId: string, creditId: string, body: { decision?: unknown; reason?: unknown; stepUpEvidenceId?: unknown }) {
    enabled(); await this.internal(actor, "COMMERCIAL_CREDIT_REVIEW"); const credit = await this.db.customerCreditCorrection.findUnique({ where: { id: creditId }, include: { customerContract: true, invoiceStatement: true } }); if (!credit || credit.customerContract.institutionId !== institutionId) throw new NotFoundException("credit not found"); if (credit.status !== "PROPOSED") throw new ConflictException("credit is not pending"); if (credit.proposedByUserId === actor.actorUserId) throw new ForbiddenException("credit proposer cannot review the same proposal"); const decision = oneOf(body.decision, "decision", ["APPROVE", "REJECT"]); const stepUpEvidenceId = required(body.stepUpEvidenceId, "stepUpEvidenceId", 160);
    return this.db.$transaction(async (tx) => { await this.consumeInternal(tx, actor, "INTERNAL_CREDIT_REVIEW", stepUpEvidenceId); await tx.$queryRaw(Prisma.sql`SELECT "id" FROM "CustomerInvoiceStatement" WHERE "id" = ${credit.invoiceStatementId} FOR UPDATE`); const current = await tx.customerCreditCorrection.findUniqueOrThrow({ where: { id: creditId }, include: { invoiceStatement: true } }); if (current.status !== "PROPOSED") throw new ConflictException("credit was concurrently decided"); if (decision === "APPROVE") { const creditTotal = await tx.customerCreditCorrection.findMany({ where: { invoiceStatementId: current.invoiceStatementId, status: "APPROVED" }, select: { amountMinor: true } }); const total = creditTotal.reduce((sum, item) => sum + BigInt(item.amountMinor), BigInt(current.amountMinor)); if (total > BigInt(current.invoiceStatement.grossFeeMinor)) throw new ConflictException("approved credits cannot exceed gross fee"); await tx.customerInvoiceStatement.update({ where: { id: current.invoiceStatementId }, data: { creditMinor: total.toString(), netFeeMinor: (BigInt(current.invoiceStatement.grossFeeMinor) - total).toString(), status: "CORRECTED" } }); } const claimed = await tx.customerCreditCorrection.updateMany({ where: { id: creditId, status: "PROPOSED" }, data: { status: decision === "APPROVE" ? "APPROVED" : "REJECTED", reviewedByUserId: actor.actorUserId, reviewStepUpId: stepUpEvidenceId, reviewReason: required(body.reason, "reason", 1_000), reviewedAt: new Date() } }); if (claimed.count !== 1) throw new ConflictException("credit was concurrently decided"); return tx.customerCreditCorrection.findUniqueOrThrow({ where: { id: creditId } }); });
  }

  async createCohort(actor: InternalOpsActor, institutionId: string, body: { customerContractId?: unknown; cohortRef?: unknown; routes?: unknown; gateRefs?: unknown; startsAt?: unknown; endsAt?: unknown; ownerUserId?: unknown; reason?: unknown; stepUpEvidenceId?: unknown }) {
    enabled(); await this.internal(actor, "CUSTOMER_COHORT_MANAGE"); const contract = await this.contract(institutionId, required(body.customerContractId, "customerContractId", 160)); if (contract.status !== "ACTIVE_SHADOW") throw new ConflictException("cohort requires an active shadow contract"); const startsAt = date(body.startsAt, "startsAt"); const endsAt = date(body.endsAt, "endsAt"); if (endsAt <= startsAt || startsAt < contract.effectiveAt || endsAt > contract.expiresAt) throw new BadRequestException("cohort term must be within contract term"); const stepUpEvidenceId = required(body.stepUpEvidenceId, "stepUpEvidenceId", 160);
    return this.db.$transaction(async (tx) => { await this.consumeInternal(tx, actor, "INTERNAL_COHORT_MANAGE", stepUpEvidenceId); return tx.customerImplementationCohort.create({ data: { id: `cohort_${randomUUID()}`, institutionId, customerContractId: contract.id, cohortRef: required(body.cohortRef, "cohortRef", 160), operatingMode: "SHADOW", routes: json(body.routes), gateRefs: json(body.gateRefs), startsAt, endsAt, ownerUserId: required(body.ownerUserId, "ownerUserId", 160), changeReason: required(body.reason, "reason", 1_000), changedByUserId: actor.actorUserId, changeStepUpId: stepUpEvidenceId } }); });
  }

  async createServiceRequest(actor: ParticipantOpsActor, body: { transactionCaseId?: unknown; requestRef?: unknown; requestType?: unknown; priority?: unknown; subject?: unknown; description?: unknown; evidenceRefs?: unknown; stepUpEvidenceId?: unknown }) {
    enabled(); const authority = await this.participant(actor, "CREATE_SERVICE_REQUEST"); const priority = oneOf(body.priority, "priority", ["LOW", "NORMAL", "HIGH", "CRITICAL"]); const now = new Date(); const slaHours = { LOW: 72, NORMAL: 24, HIGH: 4, CRITICAL: 1 }[priority]!; const stepUpEvidenceId = required(body.stepUpEvidenceId, "stepUpEvidenceId", 160);
    const transactionCaseId = body.transactionCaseId ? required(body.transactionCaseId, "transactionCaseId", 160) : null; if (transactionCaseId) await this.requireInstitutionCase(actor.actingInstitutionId, transactionCaseId);
    return this.db.$transaction(async (tx) => { await this.stepUp.consume({ evidenceId: stepUpEvidenceId, userId: actor.actorUserId, sessionId: actor.actorSessionId, purpose: "CUSTOMER_SERVICE_REQUEST_CREATE", institutionId: actor.actingInstitutionId }, tx); return tx.customerServiceRequest.create({ data: { id: `sreq_${randomUUID()}`, institutionId: actor.actingInstitutionId, transactionCaseId, requestRef: required(body.requestRef, "requestRef", 160), requestType: required(body.requestType, "requestType", 120), priority, subject: required(body.subject, "subject", 300), description: required(body.description, "description", 4_000), evidenceRefs: json(body.evidenceRefs), slaDueAt: new Date(now.getTime() + slaHours * 60 * 60 * 1_000), escalationPath: json({ levels: ["SUPPORT_ANALYST", "MANAGER", "RISK_OR_SECURITY_AS_APPLICABLE"] }), createdByUserId: actor.actorUserId, createdByMandateId: authority.mandateId! } }); });
  }

  async addCustomerMessage(actor: ParticipantOpsActor, requestId: string, body: { body?: unknown; evidenceRefs?: unknown; stepUpEvidenceId?: unknown }) {
    enabled(); await this.participant(actor, "CREATE_SERVICE_REQUEST"); const request = await this.serviceRequest(actor.actingInstitutionId, requestId); if (["CLOSED"].includes(request.status)) throw new ConflictException("closed service request cannot receive messages"); const stepUpEvidenceId = required(body.stepUpEvidenceId, "stepUpEvidenceId", 160);
    return this.db.$transaction(async (tx) => { await this.stepUp.consume({ evidenceId: stepUpEvidenceId, userId: actor.actorUserId, sessionId: actor.actorSessionId, purpose: "CUSTOMER_SERVICE_REQUEST_MESSAGE", institutionId: actor.actingInstitutionId }, tx); return tx.customerServiceMessage.create({ data: { id: `smsg_${randomUUID()}`, customerServiceRequestId: requestId, authorType: "CUSTOMER", authorUserId: actor.actorUserId, body: required(body.body, "body", 4_000), evidenceRefs: json(body.evidenceRefs) } }); });
  }

  async manageService(actor: InternalOpsActor, institutionId: string, requestId: string, body: { status?: unknown; assignedToUserId?: unknown; body?: unknown; evidenceRefs?: unknown; escalate?: unknown; stepUpEvidenceId?: unknown }) {
    enabled(); await this.internal(actor, "CUSTOMER_SERVICE_MANAGE"); const request = await this.serviceRequest(institutionId, requestId); const status = oneOf(body.status, "status", ["ACKNOWLEDGED", "IN_PROGRESS", "WAITING_CUSTOMER", "RESOLVED", "CLOSED"]); this.validateServiceTransition(request.status, status); const stepUpEvidenceId = required(body.stepUpEvidenceId, "stepUpEvidenceId", 160); const escalate = body.escalate === true;
    return this.db.$transaction(async (tx) => { await this.consumeInternal(tx, actor, "INTERNAL_SERVICE_MANAGE", stepUpEvidenceId); const claimed = await tx.customerServiceRequest.updateMany({ where: { id: requestId, status: request.status }, data: { status, assignedToUserId: body.assignedToUserId ? required(body.assignedToUserId, "assignedToUserId", 160) : request.assignedToUserId, escalationLevel: escalate ? { increment: 1 } : undefined } }); if (claimed.count !== 1) throw new ConflictException("service request was concurrently changed"); if (body.body) await tx.customerServiceMessage.create({ data: { id: `smsg_${randomUUID()}`, customerServiceRequestId: requestId, authorType: "INTERNAL", authorUserId: actor.actorUserId, body: required(body.body, "body", 4_000), evidenceRefs: json(body.evidenceRefs) } }); return tx.customerServiceRequest.findUniqueOrThrow({ where: { id: requestId } }); });
  }

  async recordOperationalReview(actor: InternalOpsActor, institutionId: string, body: { periodStart?: unknown; periodEnd?: unknown; serviceMetrics?: unknown; openItems?: unknown; evidenceRefs?: unknown; stepUpEvidenceId?: unknown }) {
    enabled(); await this.internal(actor, "CUSTOMER_REVIEW_RECORD"); const periodStart = date(body.periodStart, "periodStart"); const periodEnd = date(body.periodEnd, "periodEnd"); if (periodEnd <= periodStart) throw new BadRequestException("review period must be ordered"); const stepUpEvidenceId = required(body.stepUpEvidenceId, "stepUpEvidenceId", 160);
    return this.db.$transaction(async (tx) => { await this.consumeInternal(tx, actor, "INTERNAL_OPERATIONAL_REVIEW", stepUpEvidenceId); return tx.customerOperationalReview.create({ data: { id: `orev_${randomUUID()}`, institutionId, periodStart, periodEnd, serviceMetrics: json(body.serviceMetrics), openItems: json(body.openItems), evidenceRefs: json(body.evidenceRefs), recordedByUserId: actor.actorUserId, stepUpEvidenceId } }); });
  }

  async exportCustomerData(actor: ParticipantOpsActor, body: { stepUpEvidenceId?: unknown }) {
    enabled(); const authority = await this.participant(actor, "EXPORT_CUSTOMER_DATA"); const institutionId = actor.actingInstitutionId; const highWaterAt = new Date(); const stepUpEvidenceId = required(body.stepUpEvidenceId, "stepUpEvidenceId", 160);
    const [institution, contracts, cohorts, requests, reviews, cases, rooms] = await Promise.all([
      this.db.institution.findUniqueOrThrow({ where: { id: institutionId }, select: { id: true, legalName: true, institutionKind: true, jurisdiction: true, legalIdentifiers: true, status: true, admission: true, members: { select: { id: true, userId: true, membershipRole: true, status: true, effectiveAt: true, expiresAt: true } }, appointments: true, routeEntitlements: true } }),
      this.db.customerContract.findMany({ where: { institutionId, status: { notIn: ["PROPOSED", "REJECTED"] } }, include: { changes: { where: { status: "APPROVED" } }, rateCards: { where: { status: { notIn: ["PROPOSED", "REJECTED"] } }, include: { feeRules: true } }, usageEvents: true, invoiceStatements: { where: { status: { not: "DRAFT" } }, include: { lines: true, creditCorrections: { where: { status: "APPROVED" } } } } } }), this.db.customerImplementationCohort.findMany({ where: { institutionId } }), this.db.customerServiceRequest.findMany({ where: { institutionId }, include: { messages: true } }), this.db.customerOperationalReview.findMany({ where: { institutionId } }),
      this.db.transactionCase.findMany({ where: { OR: [{ ownerInstitutionId: institutionId }, { parties: { some: { institutionId } } }] }, select: { id: true, caseReference: true, transactionRoute: true, representation: true, assetClass: true, lifecycleLeg: true, operatingMode: true, status: true, aggregateVersion: true, createdAt: true, updatedAt: true } }),
      this.db.caseRoom.findMany({ where: { transactionCase: { OR: [{ ownerInstitutionId: institutionId }, { parties: { some: { institutionId } } }] } }, select: { id: true, transactionCaseId: true, purpose: true, status: true, policyVersion: true, createdAt: true, closedAt: true } }),
    ]);
    const visibleCaseIds = cases.map((item) => item.id); const evidence = await this.db.evidenceObject.findMany({ where: { OR: [{ institutionId }, { AND: [{ grants: { some: { granteeInstitutionId: institutionId, status: "ACTIVE", OR: [{ expiresAt: null }, { expiresAt: { gt: highWaterAt } }] } } }, { OR: [{ transactionCaseId: null }, { transactionCaseId: { in: visibleCaseIds } }] }] }] }, select: { id: true, institutionId: true, transactionCaseId: true, evidenceType: true, classification: true, purpose: true, status: true, currentVersion: true, retentionUntilAt: true, legalHold: true, createdAt: true, updatedAt: true, versions: { select: { id: true, version: true, result: true, validationStatus: true, sourceAsOfAt: true, expiresAt: true, qualifications: true, payloadDigest: true, createdAt: true } } } });
    const data = toCanonicalValue({ exportVersion: "1.0.0", highWaterAt: highWaterAt.toISOString(), institution, contracts, cohorts, requests, reviews, cases, evidenceInventory: evidence, rooms, documentBytes: "AVAILABLE_SEPARATELY_THROUGH_RECEIPT_LOGGED_EVIDENCE_DOWNLOADS", secretsExcluded: true }); const recordCounts = { contracts: contracts.length, cohorts: cohorts.length, serviceRequests: requests.length, reviews: reviews.length, cases: cases.length, evidenceObjects: evidence.length, rooms: rooms.length }; const manifestDigest = sha256Digest(data);
    await this.db.$transaction(async (tx) => { await this.stepUp.consume({ evidenceId: stepUpEvidenceId, userId: actor.actorUserId, sessionId: actor.actorSessionId, purpose: "CUSTOMER_EXIT_EXPORT", institutionId }, tx); await tx.customerDataExitExport.create({ data: { id: `cexit_${randomUUID()}`, institutionId, exportVersion: "1.0.0", highWaterAt, recordCounts: json(recordCounts), manifestDigest, scope: json({ customerRelationship: true, caseInventory: true, evidenceInventory: true, documentBytesSeparate: true, secretsExcluded: true }), requestedByUserId: actor.actorUserId, requestedByMandateId: authority.mandateId!, stepUpEvidenceId } }); }); return { manifest: { exportVersion: "1.0.0", highWaterAt, recordCounts, manifestDigest, secretsExcluded: true }, data };
  }

  private participant(actor: ParticipantOpsActor, action: Parameters<InstitutionAccessService["requireHuman"]>[0]["action"]) { return this.participantAccess.requireHuman({ userId: actor.actorUserId, institutionId: actor.actingInstitutionId, action }); }
  private internal(actor: InternalOpsActor, permission: InternalPermission) { return this.internalAccess.require({ userId: actor.actorUserId, permission, scopeType: "GLOBAL", scopeRef: null }); }
  private consumeInternal(tx: Prisma.TransactionClient, actor: InternalOpsActor, purpose: Parameters<StepUpService["consume"]>[0]["purpose"], evidenceId: string) { return this.stepUp.consume({ evidenceId, userId: actor.actorUserId, sessionId: actor.actorSessionId, purpose, institutionId: null }, tx); }
  private async contract(institutionId: string, id: string) { const item = await this.db.customerContract.findFirst({ where: { id, institutionId } }); if (!item) throw new NotFoundException("customer contract not found"); return item; }
  private async invoice(institutionId: string, id: string) { const item = await this.db.customerInvoiceStatement.findUnique({ where: { id }, include: { customerContract: true } }); if (!item || item.customerContract.institutionId !== institutionId) throw new NotFoundException("invoice statement not found"); return item; }
  private async serviceRequest(institutionId: string, id: string) { const item = await this.db.customerServiceRequest.findFirst({ where: { id, institutionId } }); if (!item) throw new NotFoundException("service request not found"); return item; }
  private async requireInstitutionCase(institutionId: string, transactionCaseId: string) { const item = await this.db.transactionCase.findFirst({ where: { id: transactionCaseId, OR: [{ ownerInstitutionId: institutionId }, { parties: { some: { institutionId, status: "ACTIVE" } } }] }, select: { id: true } }); if (!item) throw new NotFoundException("transaction case is not visible to this institution"); }
  private feeRules(value: unknown) { if (!Array.isArray(value) || !value.length || value.length > 100) throw new BadRequestException("rules must contain 1 to 100 fee rules"); const seen = new Set<string>(); return value.map((raw) => { const item = raw as Record<string, unknown>; const rule = { transactionRoute: oneOf(item.transactionRoute, "transactionRoute", ROUTES), representation: oneOf(item.representation, "representation", REPRESENTATIONS), lifecycleLeg: oneOf(item.lifecycleLeg, "lifecycleLeg", LEGS), metric: required(item.metric, "metric", 120), feeBasis: oneOf(item.feeBasis, "feeBasis", FEE_BASES), rateValue: exact(item.rateValue, "rateValue"), minimumFeeMinor: item.minimumFeeMinor === null || item.minimumFeeMinor === undefined ? null : exact(item.minimumFeeMinor, "minimumFeeMinor"), maximumFeeMinor: item.maximumFeeMinor === null || item.maximumFeeMinor === undefined ? null : exact(item.maximumFeeMinor, "maximumFeeMinor"), roundingMode: oneOf(item.roundingMode, "roundingMode", ["DOWN", "HALF_UP"]) }; const key = `${rule.transactionRoute}|${rule.representation}|${rule.lifecycleLeg}|${rule.metric}`; if (seen.has(key)) throw new BadRequestException("duplicate fee-rule route/representation/leg/metric"); seen.add(key); try { calculateExactFee(rule as ExactFeeRule, { quantityMinor: "1", notionalMinor: "1" }); } catch (error) { throw new BadRequestException((error as Error).message); } if (rule.minimumFeeMinor && rule.maximumFeeMinor && BigInt(rule.minimumFeeMinor) > BigInt(rule.maximumFeeMinor)) throw new BadRequestException("minimumFeeMinor cannot exceed maximumFeeMinor"); return rule; }); }
  private validateContractChange(contract: { status: string; expiresAt: Date }, type: string, values: unknown) { const allowed: Record<string, string[]> = { RENEW: ["ACTIVE_SHADOW"], SUSPEND: ["ACTIVE_SHADOW"], TERMINATE: ["ACTIVE_SHADOW", "SUSPENDED"], REINSTATE: ["SUSPENDED"] }; if (!allowed[type]?.includes(contract.status)) throw new ConflictException(`${type} is invalid from ${contract.status}`); if (type === "RENEW") { const input = values as Record<string, unknown>; const expiresAt = date(input?.expiresAt, "proposedValues.expiresAt"); const renewalReviewAt = date(input?.renewalReviewAt, "proposedValues.renewalReviewAt"); if (expiresAt <= contract.expiresAt) throw new BadRequestException("renewal expiry must extend the current term"); if (renewalReviewAt <= new Date() || renewalReviewAt >= expiresAt) throw new BadRequestException("renewal review must be in the future and precede expiry"); } }
  private validateServiceTransition(from: string, to: string) { const allowed: Record<string, string[]> = { OPEN: ["ACKNOWLEDGED", "IN_PROGRESS", "CLOSED"], ACKNOWLEDGED: ["IN_PROGRESS", "WAITING_CUSTOMER", "RESOLVED", "CLOSED"], IN_PROGRESS: ["WAITING_CUSTOMER", "RESOLVED", "CLOSED"], WAITING_CUSTOMER: ["IN_PROGRESS", "RESOLVED", "CLOSED"], RESOLVED: ["IN_PROGRESS", "CLOSED"], CLOSED: [] }; if (!allowed[from]?.includes(to)) throw new ConflictException(`service request transition ${from} -> ${to} is not allowed`); }
  private appliedContractChange(type: string, values: Prisma.JsonValue): Prisma.CustomerContractUpdateInput { if (type === "SUSPEND") return { status: "SUSPENDED" }; if (type === "TERMINATE") return { status: "TERMINATED" }; if (type === "REINSTATE") return { status: "APPROVED_PENDING_CUSTOMER", participantAcceptedByUserId: null, participantMandateId: null, participantStepUpId: null, participantAcceptedAt: null }; const input = values as Record<string, unknown>; return { status: "APPROVED_PENDING_CUSTOMER", expiresAt: date(input.expiresAt, "proposedValues.expiresAt"), renewalReviewAt: date(input.renewalReviewAt, "proposedValues.renewalReviewAt"), participantAcceptedByUserId: null, participantMandateId: null, participantStepUpId: null, participantAcceptedAt: null }; }
}
