"use client";
import {useEffect,useState} from "react";
import {useParams,useRouter} from "next/navigation";
import {VenueHeader} from "@/components/VenueHeader";
import {useAuth} from "@/lib/auth-context";
import {vget,vpost,vpostRaw} from "@/lib/venue";
import {requestTotpStepUp} from "@/lib/institutions";
import "../assessment.css";
type Evidence={id:string;purpose:string;status:string;evidenceType:string;documentFamily?:{title:string};versions:{id:string;version:number;validationStatus:string}[]};
type Report={id:string;stage:string;status:string;errorCode:string|null;result?:{dataQuality?:{status:string;parsedUniqueLoanCount:number;expectedUniqueLoanCount:number;parsedPrincipalMinor:string;invalidRecords:number;duplicateRecords:number};extraction:{sourceCount:number;segmentCount:number;exceptions:{code:string;locator:string}[]};analysis:{model:string|null;qualification:string;findings:{severity:string;description:string;quote:string;locator:string}[]};release?:{method:string;outcome:string|null;expertReviewed:boolean;professionalSignoff:boolean};qualifications:string[]}};
export default function EngagementEvidencePage(){
 const {engagementId}=useParams<{engagementId:string}>();const router=useRouter();const {loading,firebaseUser,needsOnboarding,activeInstitutionId}=useAuth();
 useEffect(()=>{if(!loading&&!firebaseUser)router.replace("/login");else if(!loading&&needsOnboarding)router.replace("/onboard");},[loading,firebaseUser,needsOnboarding,router]);
 if(loading||!firebaseUser||needsOnboarding)return <><VenueHeader/><main className="assessment-plan">Loading…</main></>;
 if(!activeInstitutionId||process.env.NEXT_PUBLIC_ASSURERAIL_ENGAGEMENT_BILLING_ENABLED!=="true")return <><VenueHeader/><main className="assessment-plan">Choose an approved institution with assessment access.</main></>;
 return <><VenueHeader/><EvidenceWorkspace key={`${activeInstitutionId}:${engagementId}`} institutionId={activeInstitutionId} engagementId={engagementId}/></>;
}
function EvidenceWorkspace({institutionId,engagementId}:{institutionId:string;engagementId:string}){
 const base=`/v1/rail/institutions/${encodeURIComponent(institutionId)}`,runsPath=`${base}/engagements/${encodeURIComponent(engagementId)}/runs`;
 const [evidence,setEvidence]=useState<Evidence[]>([]),[reports,setReports]=useState<Report[]>([]),[stage,setStage]=useState("INITIAL"),[category,setCategory]=useState("LOAN_TAPE"),[replace,setReplace]=useState("");
 const [selected,setSelected]=useState<string[]>([]),[file,setFile]=useState<File|null>(null),[code,setCode]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 async function load(){const [docs,reports]=await Promise.all([vget<Evidence[]>(`${base}/evidence`),vget<Report[]>(runsPath)]);setEvidence(docs.filter(e=>e.purpose===`ASSESSMENT:${engagementId}`));setReports(reports);setSelected([]);}
 useEffect(()=>{let alive=true;Promise.all([vget<Evidence[]>(`${base}/evidence`),vget<Report[]>(runsPath)]).then(([docs,reports])=>{if(alive){setEvidence(docs.filter(e=>e.purpose===`ASSESSMENT:${engagementId}`));setReports(reports);}}).catch(e=>{if(alive)setError(e.message);});return()=>{alive=false;};},[base,runsPath,engagementId]);
 async function act(fn:()=>Promise<void>){setBusy(true);setError("");setMessage("");try{await fn();await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);setCode("");}}
 return <main className="assessment-plan engagement-journey"><a href="/workspace/assessment">← Your engagements</a><h1>Assess, prepare and improve your book</h1><p>Upload the agreed loan tape and supporting evidence. Initial Assessment is automated and unsigned. Portfolio Preparation adds qualified expert review and sign-off.</p><p className="assessment-notice">Shadow processing. Payment and clean-file checks run on the server. Reports support preparation; they do not guarantee a sale.</p>
 <section><h2>1. Upload evidence</h2><p>For automatic scope reconciliation, use <a href="/templates/assurerail-loan-tape.csv" download>the CSV loan-tape headers</a>: loan_id, party_id, party_role and principal_minor (INR paise). Use BORROWER, CO_BORROWER or LINKED_PARTY for party_role, one row per distinct loan-party pair, and repeat the same loan balance. Keep identifiers as text. Other layouts need mapping review; supporting documents can be PDF, XLSX or images.</p><fieldset disabled={busy} className="journey-form"><legend>Document details</legend><label>Paid stage<select value={stage} onChange={e=>setStage(e.target.value)}><option value="INITIAL">Initial Assessment</option><option value="PREPARATION">Portfolio Preparation</option></select></label><label>Document category<select value={category} onChange={e=>{setCategory(e.target.value);setReplace("");}}>{[["LOAN_TAPE","Loan tape"],["LOAN_AGREEMENT","Loan agreement"],["SECURITY_DOCUMENT","Security document"],["REPAYMENT_HISTORY","Repayment history"],["OTHER_EVIDENCE","Other supporting evidence"]].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>New document or correction<select value={replace} onChange={e=>setReplace(e.target.value)}><option value="">Add a document</option>{evidence.filter(e=>e.evidenceType===category).map(e=><option key={e.id} value={e.id}>Replace {e.documentFamily?.title??e.id} — version {e.versions[0]?.version}</option>)}</select></label><label>File<input type="file" accept=".csv,.xlsx,.pdf,.png,.jpg,.jpeg" onChange={e=>setFile(e.target.files?.[0]??null)}/></label></fieldset><button className="btn btn-primary" disabled={busy||!file||file.size>20*1024*1024} onClick={()=>void act(async()=>{if(!file)return;await vpostRaw(`${runsPath}/upload/${stage}`,file,{filename:file.name,contentType:file.type||(/\.csv$/i.test(file.name)?"text/csv":"application/octet-stream"),documentType:category,evidenceObjectId:replace||undefined,requestRef:crypto.randomUUID()});setMessage("Upload received. Only validated, clean evidence can be processed.");})}>Upload securely</button></section>
 <section><h2>2. Select evidence and request processing</h2><fieldset className="assessment-options" disabled={busy}><legend>Current evidence versions</legend>{evidence.map(e=>{const v=e.versions[0],available=e.status==="AVAILABLE"&&v?.validationStatus==="VALID";return <label key={e.id}><input type="checkbox" disabled={!available} checked={Boolean(v&&selected.includes(v.id))} onChange={event=>setSelected(s=>event.target.checked?[...s,v.id]:s.filter(id=>id!==v.id))}/>{e.documentFamily?.title??e.evidenceType} · v{v?.version} · {e.status}</label>;})}</fieldset>{!evidence.length&&<p>No evidence has been uploaded to this engagement.</p>}<label>Authenticator code<input inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={code} onChange={e=>setCode(e.target.value)}/></label><button className="btn btn-primary" disabled={busy||!selected.length||code.length!==6} onClick={()=>void act(async()=>{const stepUpEvidenceId=await requestTotpStepUp({code,purpose:"ENGAGEMENT_PROCESSING_REQUEST",institutionId});await vpost(runsPath,{stage,evidenceVersionIds:selected,requestRef:crypto.randomUUID(),stepUpEvidenceId});setMessage(stage==="INITIAL"?"Automated assessment queued. The unsigned report will show whether to prepare, fix and reassess, or stop.":"Preparation processing queued. A qualified expert must review and sign off before release.");})}>{stage==="INITIAL"?"Run automated assessment":"Request expert-reviewed preparation"}</button><p>The included automated reassessment allowance and window are stated in your accepted quote. Changed loan scope needs a new agreement.</p></section>
 <section><h2>3. Findings and progress</h2><button className="btn" disabled={busy} onClick={()=>void act(async()=>{})}>Refresh progress</button>{reports.map(r=><article key={r.id}><h3>{r.stage==="INITIAL"?"Initial Assessment":"Portfolio Preparation"} — {r.status.replaceAll("_"," ")}</h3>{r.errorCode&&<p>Processing needs attention. Our team will investigate before another run.</p>}{r.result&&<>{r.stage==="INITIAL"?<p><strong>{r.result.release?.outcome?.replaceAll("_"," ")??"AUTOMATED INITIAL RESULT"}</strong> · Automated and unsigned; no consultant review or professional sign-off.</p>:<p><strong>Qualified expert review:</strong> {r.status==="RELEASED"?"completed":"required before release"}.</p>}{r.result.dataQuality&&<p><strong>Loan tape: {r.result.dataQuality.status.replaceAll("_"," ")}</strong> · {r.result.dataQuality.parsedUniqueLoanCount} parsed unique loans against {r.result.dataQuality.expectedUniqueLoanCount} quoted; {r.result.dataQuality.invalidRecords} invalid rows; {r.result.dataQuality.duplicateRecords} duplicates. Parsed principal: ₹{(Number(r.result.dataQuality.parsedPrincipalMinor)/100).toLocaleString("en-IN")}. Totals cover parsed records only.</p>}<p>{r.result.extraction.sourceCount} sources; {r.result.extraction.segmentCount} extracted sections. AI: {r.result.analysis.model??"not run"}. {r.result.analysis.qualification.replaceAll("_"," ")}</p>{r.result.analysis.findings.map((f,i)=><div key={i}><h4>{f.severity}: {f.description}</h4><blockquote>{f.quote}</blockquote><p>Source location: {f.locator}</p></div>)}{r.result.extraction.exceptions.map((e,i)=><p key={i}>{e.locator}: {e.code.replaceAll("_"," ")}</p>)}<p>{r.result.qualifications.map(q=>q.replaceAll("_"," ").toLowerCase()).join("; ")}. No findings does not establish eligibility or completeness.</p></>}</article>)}</section>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</main>;
}
