#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# AssureRail Daily Shadow QA (scheduled daily — see the "com.assurerail.daily-qa" launchd job)
# The venue analogue of scripts/daily-shadow-qa.sh, in its OWN shadow worktree (Code-shadow-arail) so
# it never races the AssureLocker daily. Steps:
#   1. Pull latest main (ff-only)
#   2. Rebuild the venue SHADOW worktree at origin/main (isolated from local dev)
#   3. Deps ONLINE (npm install offline-first + the venue's OWN prisma client) — only phase with egress
#   4. NO-EGRESS build of apps/assurerail-api under macOS sandbox-exec (build-time egress = a bug)
#   5. Venue unit tests (k-anon, tape integrity) on the compiled dist
#   6. AssureRail invariants (secrets/CORS/ledger-atomicity/segregation) on the shadow source
#   7. scripts/security-scan-local.sh (gitleaks / trivy / semgrep)
#   8. scripts/assurerail-strix-daily.sh (timeboxed autonomous scan of the venue source)
#   9. Dated report → docs/qa/daily/arail/DAILY_ARAIL_<date>.md (+ exit 1 if any gate failed)
# Fail-soft: every step records PASS/FAIL/SKIP; the run always produces a report.
# ─────────────────────────────────────────────────────────────────────────────
set -u
export CHECKPOINT_DISABLE=1 NEXT_TELEMETRY_DISABLED=1 TURBO_TELEMETRY_DISABLED=1 CI=1

REPO="/Users/DNorman/Development/Code"
SHADOW="/Users/DNorman/Development/Code-shadow-arail"
DATE=$(date +%F)
REPORT_DIR="$REPO/docs/qa/daily/arail"
REPORT="$REPORT_DIR/DAILY_ARAIL_${DATE}.md"
NO_EGRESS='(version 1)(allow default)(deny network*)'
mkdir -p "$REPORT_DIR"

PASS=(); FAIL=(); SKIP=()
hdr() { printf '\n## %s\n\n```\n' "$1" >>"$REPORT"; }
end() { printf '```\n%s\n' "$1" >>"$REPORT"; }
step() { # step <name> <cmd...>
  # Exit convention (mirrors scripts/daily-shadow-qa.sh): 0 = PASS · 3 = SKIP (a missing prereq — a
  # NON-RUN, never a pass) · other = FAIL. Without the rc=3 branch a scan that never ran (Docker down,
  # no API key) reported a green ✓ PASS — the 2026-07-27 regression, which was fixed on the main rail
  # but left open on this venue rail despite the AssureRail security-parity requirement.
  local name="$1"; shift; hdr "$name"; local out rc; out=$(mktemp)
  "$@" >"$out" 2>&1; rc=$?
  if [ "$rc" -eq 0 ]; then tail -n 25 "$out" >>"$REPORT"; end "**✓ PASS — $name**"; PASS+=("$name")
  elif [ "$rc" -eq 3 ]; then tail -n 25 "$out" >>"$REPORT"; end "**⚠ SKIP — $name**"; SKIP+=("$name")
  else tail -n 60 "$out" >>"$REPORT"; end "**✗ FAIL — $name**"; FAIL+=("$name"); fi
  rm -f "$out"; }
skip() { hdr "$1"; echo "$2" >>"$REPORT"; end "**⚠ SKIP — $1**"; SKIP+=("$1"); }

{ echo "# AssureRail Daily Shadow QA — $DATE"; echo ""; echo "_Machine-generated by scripts/assurerail-daily-qa.sh (venue-scoped). Triage appends the “Bugs & Fixes” section._"; } >"$REPORT"

# ── 1. latest code ────────────────────────────────────────────────────────────
cd "$REPO" || exit 1
step "Pull latest main (ff-only)" git pull --ff-only origin main

# ── 2. venue shadow worktree at origin/main ──────────────────────────────────
if [ ! -d "$SHADOW" ]; then
  step "Create venue shadow worktree" git worktree add "$SHADOW" --detach origin/main
else
  step "Reset venue shadow worktree" bash -c "cd '$SHADOW' && git fetch origin && git reset --hard origin/main && git clean -fdq -e node_modules -e .next"
fi
cd "$SHADOW" || { echo "shadow worktree missing" >>"$REPORT"; exit 1; }
echo -e "\nShadow HEAD: $(git rev-parse --short HEAD)" >>"$REPORT"

# ── 3. deps (ONLINE phase) ───────────────────────────────────────────────────
export npm_config_python="/usr/local/bin/python3.12"
export PYTHON="/usr/local/bin/python3.12"
if [ ! -d "$SHADOW/node_modules/@nestjs" ]; then
  echo "seeding shadow node_modules from main…"; rsync -a "$REPO/node_modules/" "$SHADOW/node_modules/" 2>/dev/null
fi
step "Shadow deps (npm install, offline-first)" bash -c "cd '$SHADOW' && npm install --prefer-offline --no-audit --no-fund"
step "Venue prisma client" bash -c "cd '$SHADOW' && npx prisma generate --schema apps/assurerail-api/prisma/schema.prisma"

# ── 4. NO-EGRESS builds ──────────────────────────────────────────────────────
# @code/shared must be COMPILED first: the venue imports it (tape types) and resolves it via the
# node_modules workspace symlink → packages/shared/dist. A fresh shadow worktree has no dist (build
# artifact, git-cleaned), so without this the venue tsc dies with TS2307 "Cannot find module
# '@code/shared'". Egress-free — deps are already installed in phase 3. Mirrors scripts/daily-shadow-qa.sh.
step "NO-EGRESS build — @code/shared" sandbox-exec -p "$NO_EGRESS" bash -c "cd '$SHADOW/packages/shared' && npm run build"
step "NO-EGRESS build — venue api (tsc)" sandbox-exec -p "$NO_EGRESS" bash -c "cd '$SHADOW/apps/assurerail-api' && npx tsc"

# ── 5. venue unit tests (compiled dist) ──────────────────────────────────────
step "Venue unit tests (k-anon, tape integrity)" bash -c "cd '$SHADOW/apps/assurerail-api' && node --test 'dist/**/*.test.js'"

# ── 6. venue invariants (secrets / CORS / ledger atomicity / segregation) ────
step "AssureRail invariants" bash -c "cd '$SHADOW' && node '$REPO/scripts/check-assurerail-invariants.mjs'"

# ── 7. security scan ─────────────────────────────────────────────────────────
if [ -x "$REPO/scripts/security-scan-local.sh" ]; then
  step "Local security scan (gitleaks/trivy/semgrep)" bash -c "cd '$SHADOW' && '$REPO/scripts/security-scan-local.sh'"
else
  skip "Local security scan" "scripts/security-scan-local.sh not found/executable"
fi

# ── 8. Strix autonomous security agent (venue-scoped) ────────────────────────
if [ -x "$REPO/scripts/assurerail-strix-daily.sh" ]; then
  step "AssureRail Strix (timeboxed)" "$REPO/scripts/assurerail-strix-daily.sh" "$SHADOW"
else
  skip "AssureRail Strix" "scripts/assurerail-strix-daily.sh missing"
fi

# ── 9. summary ───────────────────────────────────────────────────────────────
{
  echo ""; echo "## Summary"; echo ""
  echo "| Result | Count | Steps |"; echo "|---|---|---|"
  echo "| ✓ PASS | ${#PASS[@]} | ${PASS[*]:-—} |"
  echo "| ✗ FAIL | ${#FAIL[@]} | ${FAIL[*]:-—} |"
  echo "| ⚠ SKIP | ${#SKIP[@]} | ${SKIP[*]:-—} |"
} >>"$REPORT"

echo "REPORT: $REPORT"

# Failure + SKIP notification, and a machine-readable .status.json beside the report. A FAIL used
# to be discoverable only by opening the markdown, and a rail that stopped running announced
# itself purely by silence. Best-effort: never fails the run.
node "$REPO/scripts/qa/notify-daily-status.mjs" report --rail=AssureRail --report="$REPORT" \
  --pass=${#PASS[@]} --fail=${#FAIL[@]} --skip=${#SKIP[@]} 2>/dev/null || true
# Heartbeat: shout if the newest report is stale (i.e. the schedule stopped firing at all).
node "$REPO/scripts/qa/notify-daily-status.mjs" heartbeat --rail=AssureRail \
  --dir=docs/qa/daily/arail --prefix=DAILY_ARAIL_ --max-age-days=2 2>/dev/null || true
[ ${#FAIL[@]} -eq 0 ]
