#!/usr/bin/env bash
# PR-16 disposable structural rehearsal; synthetic rows cannot close PTC external gates.
set -euo pipefail
REPO_ROOT="$(git rev-parse --show-toplevel)"; RAIL_DIR="$REPO_ROOT/apps/assurerail-api"
TEST_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/assurerail-pr16.XXXXXX")"; PG_DATA="$TEST_ROOT/postgres"; PG_SOCKET="$TEST_ROOT/socket"; PG_LOG="$TEST_ROOT/postgres.log"
PG_PORT="$((65300 + ($$ % 100)))"; PG_USER="$(id -un)"; FRESH_DB="assurerail_pr16_fresh"; RESTORE_DB="assurerail_pr16_restore"
case "$TEST_ROOT" in */assurerail-pr16.*) ;; *) echo "unsafe scratch path" >&2; exit 1 ;; esac
for item in initdb pg_ctl createdb psql pg_dump pg_restore npx; do command -v "$item" >/dev/null || { echo "missing $item" >&2; exit 1; }; done
cleanup(){ if [[ -f "$PG_DATA/postmaster.pid" ]]; then pg_ctl -D "$PG_DATA" -m fast -w stop >/dev/null 2>&1 || true; fi; case "$TEST_ROOT" in */assurerail-pr16.*) rm -rf -- "$TEST_ROOT" ;; esac; }; trap cleanup EXIT INT TERM
mkdir -p "$PG_SOCKET"; initdb -D "$PG_DATA" --auth=trust --no-locale -E UTF8 >/dev/null; pg_ctl -D "$PG_DATA" -l "$PG_LOG" -o "-F -h 127.0.0.1 -p $PG_PORT -k $PG_SOCKET" -w start >/dev/null
db_url(){ printf 'postgresql://%s@127.0.0.1:%s/%s' "$PG_USER" "$PG_PORT" "$1"; }; psql_db(){ local db="$1"; shift; psql -X -v ON_ERROR_STOP=1 -h 127.0.0.1 -p "$PG_PORT" -U "$PG_USER" -d "$db" "$@"; }
echo "[PR16-DB] fresh migration deploy"; createdb -h 127.0.0.1 -p "$PG_PORT" -U "$PG_USER" "$FRESH_DB"; (cd "$RAIL_DIR"; DATABASE_URL="$(db_url "$FRESH_DB")" npx prisma migrate deploy --schema=prisma/schema.prisma)
psql_db "$FRESH_DB" -c '
 INSERT INTO "Institution" ("id","legalName","institutionKind","jurisdiction","legalIdentifiers","status","applicantUserId","createdAt","updatedAt") VALUES
 ($$p16_o$$,$$Originator$$,$$LENDER$$,$$IN$$,$${}$$::jsonb,$$ACTIVE$$,$$u$$,now(),now()),($$p16_t$$,$$Trustee$$,$$TRUSTEE$$,$$IN$$,$${}$$::jsonb,$$ACTIVE$$,$$u$$,now(),now()),($$p16_r$$,$$RTA$$,$$RTA$$,$$IN$$,$${}$$::jsonb,$$ACTIVE$$,$$u$$,now(),now()),($$p16_a$$,$$Assurer$$,$$ASSURANCE_PROVIDER$$,$$IN$$,$${}$$::jsonb,$$ACTIVE$$,$$u$$,now(),now());
 INSERT INTO "TransactionCase" ("id","caseReference","ownerInstitutionId","transactionRoute","representation","jurisdiction","marketContext","placementOrListing","lifecycleLeg","assetClass","operatingMode","routePackRef","routePackVersion","creationIdempotencyKey","creationRequestDigest","createdByUserId","createdByMandateId","createdAt","updatedAt") VALUES ($$p16_case$$,$$P16-TOKEN-PTC$$,$$p16_o$$,$$PTC$$,$$TOKENISED$$,$$IN$$,$$DOMESTIC$$,$$PRIVATE_PLACEMENT$$,$$INITIAL_TRANSFER_OR_ISSUE$$,$$MSME_LOAN$$,$$SHADOW$$,$$assurerail://route-packs/domestic-tokenised-ptc-shadow$$,$$1.0.0$$,$$case$$,$$sha256:case$$,$$u$$,$$m$$,now(),now());
 INSERT INTO "EvidenceObject" ("id","institutionId","transactionCaseId","evidenceType","classification","purpose","status","currentVersion","retentionUntilAt","legalHold","createdByUserId","createdAt","updatedAt") VALUES ($$p16_decl_ev$$,$$p16_r$$,$$p16_case$$,$$AUTHORITATIVE_RECORD_DECLARATION$$,$$CONFIDENTIAL$$,$$Synthetic structural rehearsal only$$,$$AVAILABLE$$,0,now()+interval $$1 day$$,false,$$u$$,now(),now());
 INSERT INTO "AuthoritativeRecordDeclaration" ("id","transactionCaseId","recordType","authorityClass","recordkeeperInstitutionId","declarationEvidenceRef","declarationEvidenceDigest","declarationEvidenceObjectId","routePackRef","routePackVersion","status","createdByUserId","createdByMandateId","createdAt","updatedAt") VALUES ($$p16_decl$$,$$p16_case$$,$$DEPOSITORY_RTA_REGISTER$$,$$LEGAL_AUTHORITY$$,$$p16_r$$,$$synthetic://declaration$$,$$sha256:declaration$$,$$p16_decl_ev$$,$$assurerail://route-packs/domestic-tokenised-ptc-shadow$$,$$1.0.0$$,$$ACTIVE$$,$$u$$,$$m$$,now(),now());
 INSERT INTO "PtcTokenRepresentation" ("id","transactionCaseId","programmeReference","trustReference","classReference","trancheDefinitionDigest","trusteeInstitutionId","recordkeeperInstitutionId","assuranceProviderInstitutionId","authoritativeRecordDeclarationId","network","tokenId","authorityMode","status","routePackRef","routePackVersion","idempotencyKey","requestDigest","proposedByUserId","proposedByMandateId","proposalStepUpId","createdAt","updatedAt") VALUES ($$p16_rep$$,$$p16_case$$,$$PROGRAMME-1$$,$$TRUST-1$$,$$CLASS-A$$,$$sha256:tranche$$,$$p16_t$$,$$p16_r$$,$$p16_a$$,$$p16_decl$$,$$SYNTHETIC_NETWORK$$,$$TOKEN-CLASS-A$$,$$MIRROR$$,$$EVIDENCE_OPEN$$,$$assurerail://route-packs/domestic-tokenised-ptc-shadow$$,$$1.0.0$$,$$idem$$,$$sha256:req$$,$$u$$,$$m$$,$$step$$,now(),now());
 INSERT INTO "PtcTokenEvidenceGate" ("id","ptcTokenRepresentationId","gateCode","expectedEvidenceType","accountableInstitutionId","status","createdAt","updatedAt") VALUES ($$p16_gate$$,$$p16_rep$$,$$HISTORIC_PTC_REPLAY_ACCEPTED$$,$$HISTORIC_PTC_REPLAY_ACCEPTANCE$$,$$p16_o$$,$$OPEN$$,now(),now());
 INSERT INTO "PtcTokenActionPlan" ("id","ptcTokenRepresentationId","actionType","sequence","candidateCapabilityId","state","blockingGateCodes","planDigest","createdAt") VALUES ($$p16_plan$$,$$p16_rep$$,$$ISSUE$$,10,$$assurerail.ptc.token.issue.v1$$,$$BLOCKED$$,$$["HISTORIC_PTC_REPLAY_ACCEPTED"]$$::jsonb,$$sha256:plan$$,now());
 DO $x$ BEGIN BEGIN DELETE FROM "PtcTokenRepresentation" WHERE id=$$p16_rep$$; RAISE EXCEPTION $$history deleted$$; EXCEPTION WHEN foreign_key_violation THEN NULL; END; END $x$;' >/dev/null
echo "[PR16-DB] parity and restore"; diff="$(cd "$RAIL_DIR"; npx prisma migrate diff --from-url="$(db_url "$FRESH_DB")" --to-schema-datamodel=prisma/schema.prisma)"; case "$diff" in *PtcToken*) echo "$diff" >&2; exit 1;; esac
pg_dump -h 127.0.0.1 -p "$PG_PORT" -U "$PG_USER" -d "$FRESH_DB" -Fc -f "$TEST_ROOT/db.dump"; createdb -h 127.0.0.1 -p "$PG_PORT" -U "$PG_USER" "$RESTORE_DB"; pg_restore -h 127.0.0.1 -p "$PG_PORT" -U "$PG_USER" -d "$RESTORE_DB" --exit-on-error "$TEST_ROOT/db.dump"
rows="$(psql_db "$RESTORE_DB" -Atc 'SELECT (SELECT count(*) FROM "PtcTokenRepresentation")||$$|$$||(SELECT count(*) FROM "PtcTokenEvidenceGate")||$$|$$||(SELECT count(*) FROM "PtcTokenActionPlan");')"; [[ "$rows" == "1|1|1" ]] || exit 1
echo "[PR16-DB] PASS representation=mirror evidence=open action=blocked restore=1|1|1 external-mutation=none"
