#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# AssureRail Daily Shadow QA (scheduled daily — see the "com.assurerail.daily-qa" launchd job)
# Runs in its own configurable shadow worktree so it never races an active developer checkout. Steps:
#   1. Fetch latest main without mutating the operator's checkout
#   2. Rebuild the venue SHADOW worktree at origin/main (isolated from local dev)
#   3. Deps ONLINE (npm install offline-first + the venue's OWN prisma client) — only phase with egress
#   4. NO-EGRESS build of apps/assurerail-api under macOS sandbox-exec (build-time egress = a bug)
#   5. Venue unit tests (k-anon, tape integrity) on the compiled dist
#   6. AssureRail invariants (secrets/CORS/ledger-atomicity/segregation) on the shadow source
#   7. repository-local gitleaks, Semgrep, dependency, Trivy and SBOM scan
#   8. scripts/assurerail-strix-daily.sh (timeboxed independent scan; findings are REVIEW, not PASS)
#   9. Dated report → docs/qa/daily/arail/DAILY_ARAIL_<date>.md (+ exit 1 if any gate failed)
# Fail-soft: every step records PASS/FAIL/SKIP; the run always produces a report.
# ─────────────────────────────────────────────────────────────────────────────
set -u
export CHECKPOINT_DISABLE=1 NEXT_TELEMETRY_DISABLED=1 TURBO_TELEMETRY_DISABLED=1 CI=1

REPO="${ARAIL_REPO_ROOT:-$(git rev-parse --show-toplevel)}"
SHADOW="${ARAIL_SHADOW_ROOT:-${REPO}-shadow}"
DATE=$(date +%F)
REPORT_DIR="$REPO/docs/qa/daily/arail"
REPORT="$REPORT_DIR/DAILY_ARAIL_${DATE}.md"
NO_EGRESS='(version 1)(allow default)(deny network*)'
mkdir -p "$REPORT_DIR"

case "$SHADOW" in
  "$REPO"|"$REPO"/*)
    echo "Refusing unsafe ARAIL_SHADOW_ROOT inside the source checkout: $SHADOW" >&2
    exit 1
    ;;
esac

PASS=(); FAIL=(); SKIP=(); REVIEW=()
hdr() { printf '\n## %s\n\n```\n' "$1" >>"$REPORT"; }
end() { printf '```\n%s\n' "$1" >>"$REPORT"; }
step() { # step <name> <cmd...>
  # Exit convention: 0 = PASS · 3 = SKIP (a missing prerequisite) · 4 = REVIEW (the scanner
  # produced potential findings) · other = FAIL. A non-run or an untriaged finding is never green.
  local name="$1"; shift; hdr "$name"; local out rc; out=$(mktemp)
  "$@" >"$out" 2>&1; rc=$?
  if [ "$rc" -eq 0 ]; then tail -n 25 "$out" >>"$REPORT"; end "**✓ PASS — $name**"; PASS+=("$name")
  elif [ "$rc" -eq 3 ]; then tail -n 25 "$out" >>"$REPORT"; end "**⚠ SKIP — $name**"; SKIP+=("$name")
  elif [ "$rc" -eq 4 ]; then tail -n 60 "$out" >>"$REPORT"; end "**⚠ REVIEW — $name**"; REVIEW+=("$name")
  else tail -n 60 "$out" >>"$REPORT"; end "**✗ FAIL — $name**"; FAIL+=("$name"); fi
  rm -f "$out"
  return "$rc"
}
skip() { hdr "$1"; echo "$2" >>"$REPORT"; end "**⚠ SKIP — $1**"; SKIP+=("$1"); }

{ echo "# AssureRail Daily Shadow QA — $DATE"; echo ""; echo "_Machine-generated by scripts/assurerail-daily-qa.sh (venue-scoped). Triage appends the “Bugs & Fixes” section._"; } >"$REPORT"

# ── 1. latest code ────────────────────────────────────────────────────────────
cd "$REPO" || exit 1
step "Fetch latest main" git fetch --prune origin main || exit 1

# ── 2. venue shadow worktree at origin/main ──────────────────────────────────
if [ ! -d "$SHADOW" ]; then
  step "Create venue shadow worktree" git worktree add "$SHADOW" --detach origin/main || exit 1
  touch "$SHADOW/.assurerail-daily-shadow"
else
  if [ -L "$SHADOW" ]; then
    skip "Reset venue shadow worktree" "refusing to reset a symbolic-link shadow path"
    exit 1
  fi
  if [ ! -f "$SHADOW/.assurerail-daily-shadow" ]; then
    skip "Reset venue shadow worktree" "refusing to reset an existing directory without .assurerail-daily-shadow"
    echo "Unsafe or uninitialised shadow path: $SHADOW" >&2
    exit 1
  fi
  git -C "$SHADOW" rev-parse --is-inside-work-tree >/dev/null 2>&1 || {
    skip "Reset venue shadow worktree" "refusing to reset a directory that is not a Git worktree"
    exit 1
  }
  step "Reset venue shadow worktree" bash -c "cd '$SHADOW' && git reset --hard origin/main && git clean -fdq -e .assurerail-daily-shadow -e node_modules -e .next" || exit 1
fi
cd "$SHADOW" || { echo "shadow worktree missing" >>"$REPORT"; exit 1; }
echo -e "\nShadow HEAD: $(git rev-parse --short HEAD)" >>"$REPORT"

# ── 3. deps (ONLINE phase) ───────────────────────────────────────────────────
export npm_config_python="/usr/local/bin/python3.12"
export PYTHON="/usr/local/bin/python3.12"
if [ ! -d "$SHADOW/node_modules/@nestjs" ]; then
  echo "seeding shadow node_modules from main…"; rsync -a "$REPO/node_modules/" "$SHADOW/node_modules/" 2>/dev/null
fi
step "Shadow deps (npm ci, offline-first)" bash -c "cd '$SHADOW' && npm ci --prefer-offline --no-audit --no-fund"
step "Venue prisma client" bash -c "cd '$SHADOW/apps/assurerail-api' && npm exec -- prisma generate --schema prisma/schema.prisma"

# ── 4. NO-EGRESS builds ──────────────────────────────────────────────────────
step "NO-EGRESS build — venue api (tsc)" sandbox-exec -p "$NO_EGRESS" bash -c "cd '$SHADOW/apps/assurerail-api' && npx tsc"

# ── 5. venue unit tests (compiled dist) ──────────────────────────────────────
step "Venue unit tests (k-anon, tape integrity)" bash -c "cd '$SHADOW/apps/assurerail-api' && node --test 'dist/**/*.test.js'"

# ── 6. venue invariants (secrets / CORS / ledger atomicity / segregation) ────
step "AssureRail invariants" bash -c "cd '$SHADOW' && node scripts/check-assurerail-invariants.mjs"
step "Repository format and configuration integrity" bash -c "cd '$SHADOW' && node scripts/check-assurerail-format.mjs"

# ── 7. security scan ─────────────────────────────────────────────────────────
step "Local security scan (gitleaks/Semgrep/SCA/Trivy/SBOM)" bash -c "cd '$SHADOW' && bash scripts/assurerail-security-scan-local.sh --full"

# ── 8. Strix autonomous security agent (venue-scoped) ────────────────────────
if [ -x "$REPO/scripts/assurerail-strix-daily.sh" ]; then
  step "AssureRail Strix (timeboxed)" "$REPO/scripts/assurerail-strix-daily.sh" "$SHADOW"
else
  skip "AssureRail Strix" "scripts/assurerail-strix-daily.sh missing"
fi

# ── 9. summary ───────────────────────────────────────────────────────────────
{
  echo ""; echo "## Summary"; echo ""
  echo "| Result | Count | Steps |"; echo "|---|---|---|"
  echo "| ✓ PASS | ${#PASS[@]} | ${PASS[*]:-—} |"
  echo "| ✗ FAIL | ${#FAIL[@]} | ${FAIL[*]:-—} |"
  echo "| ⚠ SKIP | ${#SKIP[@]} | ${SKIP[*]:-—} |"
  echo "| ⚠ REVIEW | ${#REVIEW[@]} | ${REVIEW[*]:-—} |"
} >>"$REPORT"

echo "REPORT: $REPORT"

# Alert delivery belongs to the standalone monitoring environment and is configured there. This
# script always leaves a local report. FAIL, REVIEW and SKIP all return distinct non-zero states so a
# missing security leg can never appear as a green daily run.
[ ${#FAIL[@]} -gt 0 ] && exit 1
[ ${#REVIEW[@]} -gt 0 ] && exit 4
[ ${#SKIP[@]} -gt 0 ] && exit 3
exit 0
