"use client";

import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { VenueHeader } from "@/components/VenueHeader";
import { useAuth } from "@/lib/auth-context";
import { tokenisedProductEnabled } from "@/lib/customer-workspace";
import { requestTotpStepUp } from "@/lib/institutions";
import { vget, vpost } from "@/lib/venue";

type Stage = { code: string; state: string; summary: string };
type Gate = { gateCode: string; expectedEvidenceType: string; accountableInstitutionId: string; status: string; evidenceObjectId: string | null; evidenceDigest: string | null };
type Action = { id: string; sequence: number; actionType: string; executionMode: string; state: string; expectedDigest: string | null; instructionRequestDigest: string | null; acknowledgements: Array<{ id: string; status: string; finalityClass: string; signatureStatus: string }> };
type Representation = { id: string; noteId?: string; programmeReference?: string; trustReference?: string; classReference?: string;
  trusteeInstitutionId?: string; recordkeeperInstitutionId?: string; assuranceProviderInstitutionId?: string | null;
  authoritativeRecordDeclarationId: string; network: string; tokenId: string; authorityMode: string; status: string;
  proposedByUserId?: string; connectorBindings?: Array<{ id: string; custodyInstitutionId: string; custodyModel: string; status: string }>;
  actions?: Action[]; latestReconciliation?: { version: number; reconciliationState: string; comparisonDigest: string | null } | null;
  breaks?: Array<{ id: string; breakCode: string; severity: string; status: string; ownerInstitutionId: string }>;
  evidenceGates?: Gate[]; actionPlans?: Array<{ actionType: string; state: string; candidateCapabilityId: string; planDigest: string | null }> };
type Overview = { operatingBoundary: "OBSERVE_ONLY"; authorityMode: "MIRROR"; dispatchPermitted: false; authorityNotice: string;
  route: "DA" | "PTC"; case: { id: string; caseReference: string; transactionRoute: string; operatingMode: string; status: string };
  stages: Stage[]; openExternalGates: Array<{ code: string; owner: string; state: string }>;
  capabilities: { canOperateRoute: boolean; canViewEvidence: boolean }; representation: Representation | null };

const parseObject = (value: string, label: string) => { const parsed: unknown = JSON.parse(value); if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new Error(`${label} must be a JSON object`); return parsed; };

export default function TokenisedJourneyPage() {
  const { caseId: raw } = useParams<{ caseId: string }>(); const caseId = decodeURIComponent(raw);
  const router = useRouter(); const { loading, firebaseUser, venueUser, needsOnboarding, activeInstitutionId } = useAuth();
  const [data, setData] = useState<Overview | null>(null); const [totp, setTotp] = useState(""); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const [link, setLink] = useState({ noteId: "", declarationId: "", network: "", unitsScale: 0 });
  const [action, setAction] = useState({ providerReferenceId: "", actionType: "MINT", expected: '{"unitsMinor":"1"}' });
  const [observation, setObservation] = useState({ actionId: "", acknowledgementId: "", status: "SUCCEEDED", finalityClass: "FINAL", signatureStatus: "VERIFIED", acknowledgedAt: "", evidenceObjectId: "", response: "{}" });
  const [reconcile, setReconcile] = useState({ tokenSupplyMinor: "", tokenHoldings: "{}", economicInterests: "{}", authoritativeRecord: "{}", evidenceObjectId: "", sourceAsOfAt: "" });
  const [ptc, setPtc] = useState({ programmeReference: "", trustReference: "", classReference: "", trancheDefinitionDigest: "", trusteeInstitutionId: "", recordkeeperInstitutionId: "", assuranceProviderInstitutionId: "", declarationId: "", network: "", tokenId: "", evidenceByGate: "{}" });
  const [gate, setGate] = useState({ code: "", evidenceObjectId: "" }); const keys = useRef<Record<string, string>>({});
  const enabled = tokenisedProductEnabled(); const productRoot = `/v1/rail/cases/${encodeURIComponent(caseId)}/tokenised-product`;
  const load = useCallback(async () => {
    if (!enabled || !activeInstitutionId) return;
    try { const next = await vget<Overview>(productRoot); setData(next); setGate((current) => ({ ...current, code: current.code || next.representation?.evidenceGates?.find((item) => item.status !== "VERIFIED")?.gateCode || "" })); setError(""); }
    catch (cause) { setError((cause as Error).message); }
  }, [activeInstitutionId, enabled, productRoot]);
  useEffect(() => { if (!loading && !firebaseUser) router.replace("/login"); else if (!loading && needsOnboarding) router.replace("/onboard"); }, [loading, firebaseUser, needsOnboarding, router]);
  useEffect(() => { if (firebaseUser && activeInstitutionId && enabled) void load(); }, [firebaseUser, activeInstitutionId, enabled, load]);
  function key(scope: string) { return keys.current[scope] ??= `${scope}:${crypto.randomUUID()}`; }
  async function governed(scope: string, purpose: string, path: string, body: Record<string, unknown>, message: string) {
    if (!activeInstitutionId) return; setBusy(scope); setError(""); setNotice("");
    try { const stepUpEvidenceId = await requestTotpStepUp({ code: totp, purpose, institutionId: activeInstitutionId }); await vpost(path, { ...body, idempotencyKey: key(scope), stepUpEvidenceId }); delete keys.current[scope]; setNotice(message); await load(); }
    catch (cause) { setError((cause as Error).message); } finally { setBusy(""); }
  }
  async function downloadPack() { setBusy("pack"); try { const pack = await vget<unknown>(`${productRoot}/evidence-pack`); const url = URL.createObjectURL(new Blob([JSON.stringify(pack, null, 2)], { type: "application/json" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `assurerail-tokenised-${caseId}-evidence-pack.json`; anchor.click(); URL.revokeObjectURL(url); } catch (cause) { setError((cause as Error).message); } finally { setBusy(""); } }
  const daRoot = `/v1/rail/cases/${encodeURIComponent(caseId)}/token-representation`; const ptcRoot = `/v1/rail/cases/${encodeURIComponent(caseId)}/ptc-token`;
  return <><VenueHeader/><main className="wrap institutional-page customer-workspace"><Link className="back-link" href="/workspace/tokenised">← Tokenised route register</Link>
    <div className="console-head"><p className="eyebrow">AR-28 · {data?.route ?? "tokenised"} · {data?.case.operatingMode ?? "shadow"}</p><h1>{data?.case.caseReference ?? "Tokenised route journey"}</h1><p>{data?.route === "PTC" ? "Programme, trust, tranche, assurance, trustee, recordkeeper and dormant token action controls." : "Token mirror linkage, observe-only action capture and four-way authoritative-record reconciliation."}</p></div>
    <div className="boundary-note">{data?.authorityNotice ?? "Mirror only. No token or payment action can be dispatched from this product."}</div>
    {!enabled && <div className="msg err">The tokenised route product is disabled.</div>}{error && <div className="msg err" role="alert">{error}</div>}{notice && <div className="msg ok" aria-live="polite">{notice}</div>}
    {data && <><section className="onboarding-stage-grid" aria-label="Tokenised route stages">{data.stages.map((stage, index) => <article className="onboarding-stage" key={stage.code}><span>{String(index + 1).padStart(2, "0")}</span><div><strong>{stage.code.replaceAll("_", " ")}</strong><p>{stage.summary}</p></div><em className="pill">{stage.state}</em></article>)}</section>
      <section className="panel governance-ceremony"><h2 className="section-title">Governed action ceremony</h2><label className="lbl">Authenticator code<input className="field governance-code" inputMode="numeric" autoComplete="one-time-code" value={totp} onChange={(event) => setTotp(event.target.value.replace(/\D/g, "").slice(0, 8))}/></label><p className="meta">Every mutation is re-authorised by the case-scoped API. The product flag never grants route authority.</p></section>
      <section className="workspace-grid">
        <article className="panel workspace-module"><h2>External activation gates</h2>{data.openExternalGates.map((item) => <div className="workspace-row" key={item.code}><span><strong>{item.code.replaceAll("_", " ")}</strong><small>{item.owner}</small></span><span className="pill pill-warn">{item.state}</span></div>)}</article>
        <article className="panel workspace-module"><h2>Representation boundary</h2><ul className="workspace-list"><li><span>Authority mode</span><strong>{data.authorityMode}</strong></li><li><span>Dispatch permitted</span><strong>NO</strong></li><li><span>Evidence view</span><strong>{data.capabilities.canViewEvidence ? "AVAILABLE" : "UNAVAILABLE"}</strong></li></ul>{data.representation && <button className="btn" disabled={!!busy || !data.capabilities.canViewEvidence} onClick={() => void downloadPack()}>Download evidence pack</button>}</article>
        {data.route === "DA" && !data.representation && data.capabilities.canOperateRoute && <article className="panel workspace-module workspace-wide"><h2>Link the DA token mirror</h2><div className="governance-form"><label className="lbl">Legacy Note ID<input className="field" value={link.noteId} onChange={(e) => setLink({ ...link, noteId: e.target.value })}/></label><label className="lbl">Authoritative-record declaration ID<input className="field" value={link.declarationId} onChange={(e) => setLink({ ...link, declarationId: e.target.value })}/></label><label className="lbl">Network<input className="field" value={link.network} onChange={(e) => setLink({ ...link, network: e.target.value })}/></label><label className="lbl">Units scale<input className="field" type="number" min="0" max="18" value={link.unitsScale} onChange={(e) => setLink({ ...link, unitsScale: Number(e.target.value) })}/></label><button className="btn btn-primary" disabled={!!busy || totp.length < 6} onClick={() => void governed("da-link", "TOKEN_REPRESENTATION_LINK", `${daRoot}/link`, { noteId: link.noteId, authoritativeRecordDeclarationId: link.declarationId, network: link.network, unitsScale: link.unitsScale, reason: "Link the existing token as a mirror of the declared authoritative record" }, "Token mirror linked; no token action was dispatched.")}>Link mirror</button></div></article>}
        {data.route === "DA" && data.representation && <><article className="panel workspace-module workspace-wide"><div className="workspace-module-head"><div><h2>{data.representation.network} · {data.representation.tokenId}</h2><p>Note {data.representation.noteId} · declaration {data.representation.authoritativeRecordDeclarationId}</p></div><span className="pill">{data.representation.status}</span></div><div className="record-list">{data.representation.connectorBindings?.map((item) => <div className="workspace-row" key={item.id}><span><strong>{item.custodyModel}</strong><small>{item.custodyInstitutionId}</small></span><span className="pill">{item.status}</span></div>)}{!data.representation.connectorBindings?.length && <p className="meta">No active connector/custody binding. External certification and acceptance remain open.</p>}</div></article>
          {data.capabilities.canOperateRoute && <article className="panel workspace-module workspace-wide"><h2>Prepare an observe-only token action</h2><div className="governance-form"><label className="lbl">Provider reference ID<input className="field" value={action.providerReferenceId} onChange={(e) => setAction({ ...action, providerReferenceId: e.target.value })}/></label><label className="lbl">Action type<select className="field" value={action.actionType} onChange={(e) => setAction({ ...action, actionType: e.target.value })}>{["MINT","TRANSFER","PAYMENT","ANCHOR","AMORTISE_BURN","CLOSE_BURN"].map((value) => <option key={value}>{value}</option>)}</select></label><label className="lbl">Expected fact JSON<textarea className="field" rows={4} value={action.expected} onChange={(e) => setAction({ ...action, expected: e.target.value })}/></label><button className="btn btn-primary" disabled={!!busy || totp.length < 6} onClick={() => { try { void governed("da-action", "TOKEN_ACTION_PREPARE", `${daRoot}/actions`, { providerReferenceId: action.providerReferenceId, actionType: action.actionType, expected: parseObject(action.expected, "Expected fact"), reason: "Prepare an observe-only token action for external comparison" }, "Observe-only action prepared; dispatch is prohibited."); } catch (cause) { setError((cause as Error).message); } }}>Prepare observation</button></div></article>}
          <article className="panel workspace-module workspace-wide"><h2>Observed actions</h2>{data.representation.actions?.map((item) => <div className="workspace-row" key={item.id}><span><strong>{item.sequence}. {item.actionType}</strong><small>{item.executionMode} · {item.acknowledgements.length} acknowledgement(s)</small></span><span className="pill">{item.state}</span></div>)}{!data.representation.actions?.length && <p className="meta">No external action has been observed.</p>}</article>
          {data.capabilities.canOperateRoute && <article className="panel workspace-module workspace-wide"><h2>Record an authenticated external observation</h2><div className="governance-form"><label className="lbl">Prepared action<select className="field" value={observation.actionId} onChange={(e) => setObservation({ ...observation, actionId: e.target.value })}><option value="">Select</option>{data.representation.actions?.map((item) => <option value={item.id} key={item.id}>{item.sequence}. {item.actionType}</option>)}</select></label><label className="lbl">External acknowledgement ID<input className="field" value={observation.acknowledgementId} onChange={(e) => setObservation({ ...observation, acknowledgementId: e.target.value })}/></label><label className="lbl">Acknowledged at<input className="field" type="datetime-local" value={observation.acknowledgedAt} onChange={(e) => setObservation({ ...observation, acknowledgedAt: e.target.value })}/></label><label className="lbl">Evidence object ID<input className="field" value={observation.evidenceObjectId} onChange={(e) => setObservation({ ...observation, evidenceObjectId: e.target.value })}/></label><label className="lbl">Signed response JSON<textarea className="field" rows={4} value={observation.response} onChange={(e) => setObservation({ ...observation, response: e.target.value })}/></label><button className="btn btn-primary" disabled={!!busy || totp.length < 6 || !observation.actionId} onClick={() => { try { void governed(`da-observe:${observation.actionId}`, "TOKEN_ACTION_OBSERVE", `${daRoot}/actions/${encodeURIComponent(observation.actionId)}/observations`, { externalAcknowledgementId: observation.acknowledgementId, status: observation.status, finalityClass: observation.finalityClass, signatureStatus: observation.signatureStatus, acknowledgedAt: new Date(observation.acknowledgedAt).toISOString(), evidenceObjectId: observation.evidenceObjectId, response: parseObject(observation.response, "Signed response"), reason: "Record the authenticated provider observation" }, "External observation retained; Rail did not perform the action."); } catch (cause) { setError((cause as Error).message); } }}>Record observation</button></div></article>}
          {data.capabilities.canOperateRoute && <article className="panel workspace-module workspace-wide"><h2>Four-way reconciliation</h2><div className="governance-form"><label className="lbl">Token supply minor units<input className="field" inputMode="numeric" value={reconcile.tokenSupplyMinor} onChange={(e) => setReconcile({ ...reconcile, tokenSupplyMinor: e.target.value })}/></label><label className="lbl">Source as-of<input className="field" type="datetime-local" value={reconcile.sourceAsOfAt} onChange={(e) => setReconcile({ ...reconcile, sourceAsOfAt: e.target.value })}/></label>{(["tokenHoldings","economicInterests","authoritativeRecord"] as const).map((name) => <label className="lbl" key={name}>{name.replaceAll(/([A-Z])/g, " $1")} JSON<textarea className="field" rows={3} value={reconcile[name]} onChange={(e) => setReconcile({ ...reconcile, [name]: e.target.value })}/></label>)}<label className="lbl">Evidence object ID<input className="field" value={reconcile.evidenceObjectId} onChange={(e) => setReconcile({ ...reconcile, evidenceObjectId: e.target.value })}/></label><button className="btn btn-primary" disabled={!!busy || totp.length < 6} onClick={() => { try { void governed("da-reconcile", "TOKEN_RECONCILIATION_RECORD", `${daRoot}/reconciliations`, { tokenSupplyMinor: reconcile.tokenSupplyMinor, tokenHoldings: parseObject(reconcile.tokenHoldings, "Token holdings"), economicInterests: parseObject(reconcile.economicInterests, "Economic interests"), authoritativeRecord: parseObject(reconcile.authoritativeRecord, "Authoritative record"), evidenceObjectId: reconcile.evidenceObjectId, sourceAsOfAt: new Date(reconcile.sourceAsOfAt).toISOString(), reason: "Compare the token mirror with economic interests and the declared authoritative record" }, "Reconciliation recorded; any mismatch remains a blocking break."); } catch (cause) { setError((cause as Error).message); } }}>Record reconciliation</button></div></article>}
        </>}
        {data.route === "PTC" && !data.representation && data.capabilities.canOperateRoute && <article className="panel workspace-module workspace-wide"><h2>Propose the separately governed PTC mirror</h2><div className="governance-form">{(["programmeReference","trustReference","classReference","trancheDefinitionDigest","trusteeInstitutionId","recordkeeperInstitutionId","assuranceProviderInstitutionId","network","tokenId"] as const).map((name) => <label className="lbl" key={name}>{name.replaceAll(/([A-Z])/g, " $1")}<input className="field" value={ptc[name]} onChange={(e) => setPtc({ ...ptc, [name]: e.target.value })}/></label>)}<label className="lbl">Authoritative-record declaration ID<input className="field" value={ptc.declarationId} onChange={(e) => setPtc({ ...ptc, declarationId: e.target.value })}/></label><label className="lbl">Optional gate-code to evidence-ID JSON<textarea className="field" rows={4} value={ptc.evidenceByGate} onChange={(e) => setPtc({ ...ptc, evidenceByGate: e.target.value })}/></label><button className="btn btn-primary" disabled={!!busy || totp.length < 6} onClick={() => { try { void governed("ptc-propose", "PTC_TOKEN_REPRESENTATION_PROPOSE", ptcRoot, { ...ptc, authoritativeRecordDeclarationId: ptc.declarationId, evidenceByGate: parseObject(ptc.evidenceByGate, "Evidence mapping"), reason: "Propose a PTC token mirror with all unavailable external gates left open" }, "PTC mirror proposed; no issue, allotment or token action occurred."); } catch (cause) { setError((cause as Error).message); } }}>Propose mirror</button></div></article>}
        {data.route === "PTC" && data.representation && <><article className="panel workspace-module workspace-wide"><div className="workspace-module-head"><div><h2>{data.representation.programmeReference} · {data.representation.classReference}</h2><p>{data.representation.trustReference} · {data.representation.network}/{data.representation.tokenId}</p></div><span className="pill">{data.representation.status}</span></div><p className="meta">Trustee {data.representation.trusteeInstitutionId} · recordkeeper {data.representation.recordkeeperInstitutionId} · assurance {data.representation.assuranceProviderInstitutionId ?? "not assigned"}</p></article>
          <article className="panel workspace-module workspace-wide"><h2>External evidence gates</h2>{data.representation.evidenceGates?.map((item) => <div className="workspace-row" key={item.gateCode}><span><strong>{item.gateCode.replaceAll("_", " ")}</strong><small>{item.expectedEvidenceType} · owner {item.accountableInstitutionId}</small></span><span className={`pill ${item.status === "VERIFIED" ? "pill-ok" : "pill-warn"}`}>{item.status}</span></div>)}</article>
          {data.representation.status === "EVIDENCE_OPEN" && data.capabilities.canOperateRoute && <article className="panel workspace-module"><h2>Link current gate evidence</h2><label className="lbl">Open gate<select className="field" value={gate.code} onChange={(e) => setGate({ ...gate, code: e.target.value })}><option value="">Select</option>{data.representation.evidenceGates?.filter((item) => item.status !== "VERIFIED").map((item) => <option key={item.gateCode}>{item.gateCode}</option>)}</select></label><label className="lbl">Evidence object ID<input className="field" value={gate.evidenceObjectId} onChange={(e) => setGate({ ...gate, evidenceObjectId: e.target.value })}/></label><button className="btn btn-primary" disabled={!!busy || totp.length < 6 || !gate.code} onClick={() => void governed(`ptc-gate:${gate.code}`, "PTC_TOKEN_EVIDENCE_RECORD", `${ptcRoot}/${encodeURIComponent(data.representation!.id)}/gates/${encodeURIComponent(gate.code)}/evidence`, { evidenceObjectId: gate.evidenceObjectId, reason: "Link current signed external evidence to this one PTC gate" }, "Current external evidence linked; other gates remain unchanged.")}>Link evidence</button></article>}
          {["PROPOSED","EVIDENCE_OPEN"].includes(data.representation.status) && data.representation.proposedByUserId !== venueUser?.id && data.capabilities.canOperateRoute && <article className="panel workspace-module"><h2>Independent representation review</h2><div className="button-row"><button className="btn btn-primary" disabled={!!busy || totp.length < 6} onClick={() => void governed("ptc-review:true", "PTC_TOKEN_REPRESENTATION_REVIEW", `${ptcRoot}/${encodeURIComponent(data.representation!.id)}/review`, { approved: true, reason: "Independently approve only if every current external gate is verified" }, "Shadow readiness review recorded; dispatch remains prohibited.")}>Approve shadow readiness</button><button className="btn btn-danger" disabled={!!busy || totp.length < 6} onClick={() => void governed("ptc-review:false", "PTC_TOKEN_REPRESENTATION_REVIEW", `${ptcRoot}/${encodeURIComponent(data.representation!.id)}/review`, { approved: false, reason: "Reject the proposed PTC token mirror" }, "PTC mirror rejected; retained evidence remains auditable.")}>Reject</button></div></article>}
          <article className="panel workspace-module workspace-wide"><h2>Dormant action plans</h2>{data.representation.actionPlans?.map((item) => <div className="workspace-row" key={item.actionType}><span><strong>{item.actionType}</strong><small>{item.candidateCapabilityId}</small></span><span className="pill">{item.state}</span></div>)}</article>
        </>}
      </section>
    </>}
  </main></>;
}
